### ISSUE TITLE
Do you guys have any idea to make minicap keep high fps

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [openstf/minicap#103]
**What is the issue or idea you have?**
Do you guys have any idea to make minicap keep high fps, even there aren't any changing in display.

**Comment by qmfrederik** [comment]
There's https://github.com/cfal/droid-VNC-viewer which uses the VNC protocol rather than a stream of compressed JPEG images to communicate between the device and the host.

I haven't given it a try, but some VNC algorithms may be better than turbojpeg. May be worth exploring.
