### ISSUE TITLE
Changing the quirk-bitflags

### ISSUE THREAD

**Issue by pittzgal** [openstf/minicap#104]
Hi I wrote a python client and tried to get the images. However there is some distortion and hence I was wondering if there is a way to change the quirk-bitflag from QUIRK_ALWAYS_UPRIGHT to QUIRK_DUMB so that frames get sent even when there is no change in the previous frame?
![image-9](https://user-images.githubusercontent.com/8194974/33113623-3215e170-cf94-11e7-99fd-d406ab5312d3.jpeg)

**Comment by sorccu** [comment]
No. Quirks are not configurable, they only let you know how things are.
