### ISSUE TITLE
when i run minicap on my xiaomi ,my phone got stuck

### ISSUE THREAD

**Issue by yangxinQA** [openstf/minicap#106]
**What is the issue or idea you have?**
when i run minicap on my xiaomi ,my phone got stuck.
my phone sdk version =19 
cpu is armeabi-v7a

when i run this command ,my phone got stuck
adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@1080x1920/0

while it work well with some other phone .I donot know why?could you help me ?

**Comment by sorccu** [comment]
Not enough details. I have several Xiaomi phones and all work well.

Once you start minicap, you have to connect to it and consume the frames. Otherwise it can get stuck.

**Comment by yangxinQA** [comment]
i made a mistake ,becasue i start test command and the stream shot command at the same time . as the author say 
_Once you start minicap, you have to connect to it and consume the frames. Otherwise it can get stuck._

By running shot stream command  only I solved the problem . hope helpful for others
