### ISSUE TITLE
Vnc doesn't work with Samsung Galaxy Nexus I9250

### ISSUE THREAD

**Issue by umutuzgur** [openstf/minicap#11]
I tried minicap with different phones starting from Android 2.3 until 6 but with this model it didn't work. I don't have any more 4.3 devices so I don't know if it's related to the Android version but with nexus it doesn't work. I really liked the work you did guys thou. It's cool

**Comment by sorccu** [comment]
Thanks for the detailed report! It's usually difficult for us to fix specific devices if we don't have them. I guess it's pretty unlikely, but if you happen to have an extra device laying around, considering [donating it](https://github.com/openstf/stf#sponsors-wanted) for the cause.
