### ISSUE TITLE
Forwarded screen turns blank after running minicap for 30 minutes

### ISSUE THREAD

**Issue by wangzirui** [openstf/minicap#111]
I'm testing screen capture software. I've written a C# program that takes the binary data from the socket and presents the phone image on the computer screen. My problem with minicap is that after around 30 minutes the image on my computer will turn blank. Is this because there is no Service of an app, so the program cannot run for a long time? This is just my guess. Is there a way to keep capturing running indefinitely?

**Comment by wangzirui** [comment]
Oh, what I need is this: adb shell input keyevent KEYCODE_WAKEUP.

**Comment by XiaLeon** [comment]
@wangzirui  Hi, I met the same issue, which device is yours?  Have you solved this issue ? 
Please let me know, Thanks so much !

**Comment by wangzirui** [comment]
@XiaLeon Check [this setting](https://www.techbout.com/stop-android-phone-from-turning-off-automatically-33875/). If you set the "sleep after 30 minutes" setting to "not sleep at all," then the problem is likely solved.

**Comment by XiaLeon** [comment]
@wangzirui The setting on my device is already "not sleep at all", and the problem just sometimes occurs sometimes not. So your situation is that your device screen is off when the forwarded screen turns blank, right?
