### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by canojim** [openstf/minicap#113]
Any thoughts? Thanks.

$ ndk-build
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.
[armeabi-v7a] Install        : minicap => libs/armeabi-v7a/minicap
[armeabi-v7a] Install        : minicap-nopie => libs/armeabi-v7a/minicap-nopie
[armeabi-v7a] Install        : minicap.so => libs/armeabi-v7a/minicap.so
[arm64-v8a] Compile++      : minicap-common <= SimpleServer.cpp
jni/minicap/SimpleServer.cpp: In member function 'int SimpleServer::start(const char*)':
jni/minicap/SimpleServer.cpp:28:32: error: 'memset' was not declared in this scope
   memset(&addr, 0, sizeof(addr));
                                ^
jni/minicap/SimpleServer.cpp:30:55: error: 'strlen' was not declared in this scope
   strncpy(&addr.sun_path[1], sockname, strlen(sockname));
                                                       ^
jni/minicap/SimpleServer.cpp:30:56: error: 'strncpy' was not declared in this scope
   strncpy(&addr.sun_path[1], sockname, strlen(sockname));
                                                        ^
make: *** [obj/local/arm64-v8a/objs/minicap-common/SimpleServer.o] Error 1

---
ndk-build -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

**Comment by VladX09** [comment]
Same with NDK 16.1.4479499

**Comment by sorccu** [comment]
PR accepted.
