### ISSUE TITLE
有病啊，为什么不提供编译好的文件

### ISSUE THREAD

**Issue by hzh86316** [openstf/minicap#115]
**有病啊，为什么不提供编译好的文件?**

**为什么不提供编译好的文件?为什么不提供编译好的文件?为什么不提供编译好的文件?, 专门登录上来骂你**

**Comment by sorccu** [comment]
I'm not sure how accurate Google Translate was, but it seems like you're complaining that our free work is not provided for you on a silver plate? You are most welcome to not use our software.
