### ISSUE TITLE
Android 8.1.0，Why minicap can not work in horizontal mode，only show half screen。

### ISSUE THREAD

**Issue by meng-17** [openstf/minicap#116]
Android 8.1.0，Why minicap can not work in horizontal mode，only show half screen。

**Comment by sorccu** [comment]
Change the projection and restart minicap.

**Comment by meng-17** [comment]
Log is correct， only show half screen，Google Pixel/ Android 8.1.0
INFO: Using projection 1080x1920@1080x1920/1
INFO: (external/MY_minicap/src/minicap_27.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_27.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_27.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_27.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_27.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_27.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_27.cpp:276) Publishing virtual display
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder

**Comment by meng-17** [comment]
@sorccu

**Comment by meng-17** [comment]
@sorccu 
Log is correct， only show half screen，Google Pixel/ Android 8.1.0
INFO: Using projection 1080x1920@1080x1920/1
INFO: (external/MY_minicap/src/minicap_27.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_27.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_27.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_27.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_27.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_27.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_27.cpp:276) Publishing virtual display
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder

**Comment by sorccu** [comment]
Try STF. If STF works, then you're doing it wrong. Run STF with `DEBUG=adb* stf local` and check the commands it runs.
