### ISSUE TITLE
While leaving device ideal for some time and work on another tab(google chrome), device got disconnected

### ISSUE THREAD

**Issue by varundtsfi** [openstf/minicap#117]
I am using two devices on browser and  If I am working on a device, another tab will be ideal for some time then that device got disconnected. I need to connect the device again.

Why this is happening? Is this the behavior of minicap libs? Will minicap stop sending frames If I am not using the device.

Please suggest me.

@sorccu

**Comment by sorccu** [comment]
Stop pinging me directly. Someone else might answer.

There's a 15min activity timeout by default. Check `-h` for options and look for `--group-timeout`.

**Comment by sorccu** [comment]
Oh.. this is the minicap repository. Try it out in STF and see if the same thing happens. If it doesn't it's an issue with your own code.

**Comment by varundtsfi** [comment]
It happens on STF also.

Sorry for ping you directly but I thi k hour are the correct person to give
the correct answer.
