### ISSUE TITLE
Android P

### ISSUE THREAD

**Issue by sorccu** [openstf/minicap#118]
# Android P

This is a tracking issue for Android P support.

### Current status

Not supported.

### Situation

Google has published a new AOSP branch, [android-p-preview-3](https://android.googlesource.com/). However, as usual, the published source code is out of date and doesn't actually match the published build of [`sailfish-ppp3.180510.008-factory-a0ef4945.zip`](https://developer.android.com/preview/download.html). Various symbols have changed, requiring a considerable amount of reverse engineering to get things working again without the actual source code.

### Current status

Not supported.

### Situation

Google has published a new AOSP branch, [android-p-preview-2](https://android.googlesource.com/). However, as usual, the published source code is out of date and doesn't actually match the published build of [`sailfish-ppp2.180412.013-factory-18f60ec5.zip`](https://developer.android.com/preview/download.html). Various symbols have changed, requiring a considerable amount of reverse engineering to get things working again without the actual source code.

### Current status

Not supported.

### Situation

Google has published a new AOSP branch, [android-p-preview-1](https://android.googlesource.com/). However, as usual, the published source code is out of date and doesn't actually match the published build of [`sailfish-ppp1.180208.014-factory-3e45bada.zip`](https://developer.android.com/preview/download.html). Various symbols have changed, requiring a considerable amount of reverse engineering to get things working again without the actual source code.

**Comment by weihangdong** [comment]
when minicap can support android P ? 
i try use ndk r17 beta to build minicap, but it not work.

**Comment by sorccu** [comment]
Once Google releases the actual source code they use. Which is unlikely to happen until DP 2 or 3.

If someone wants it faster I can perhaps do it, but it’ll cost quite a bit.

**Comment by weihangdong** [comment]
if i want it faster ，How to operate

**Comment by sorccu** [comment]
Email me at simo @ the name of this github org .io and tell me more about your or your company's use case.

**Comment by zuliang** [comment]
Hello, I hope to know why minicap must wait for the releasement of actual source code? I also hope it faster.

**Comment by sorccu** [comment]
Because minicap relies on private APIs. Those APIs have changed and we need to know how. It would be possible to reverse engineer the changes but I don't have time for that right now, it's easier to just wait.

**Comment by weihangdong** [comment]
dp3 punished,  the published source code match actual source code now?

**Comment by sorccu** [comment]
They haven't published the new branch yet. Latest I can see is still `android-p-preview-2`.

**Comment by sorccu** [comment]
They have published the branch but it's still not the thing they're really using.

**Comment by Master-An** [comment]
What about it now?

**Comment by sorccu** [comment]
Doesn’t seem like it but I’ll have to verify later.

**Comment by thinkhy** [comment]
I hit the same error when compiled DP4, I replied the post in the forum of [Android Buidling](https://groups.google.com/forum/#!topic/android-building/JfgzeR_S9N4), still no one can post the answer. 

For now we can only work on DP3.

**Comment by sorccu** [comment]
That one is pretty easy to fix, it’s the errors you get after that that are the most difficult. For now, to get past the setName error, you can even just comment out the line and that’ll let you proceed. Otherwise, you can use dlsym to call the right function.

**Comment by thinkhy** [comment]
After commenting out this line, still hit another error:

```
CANNOT LINK EXECUTABLE "/data/local/tmp/minicap-devel/minicap": cannot locate symbol "_ZN7android21SurfaceComposerClient21openGlobalTransactionEv" referenced by "/data/local/tmp/minicap-devel/minicap.so"...
```

I have been building an image based DP3 code for Pixel2, hope it works.

**Comment by sorccu** [comment]
Google has released the source code for the final release. I took a quick look and it seems like they've finally released the actual source code, they've got the right symbols in there. We should be able to implement P support with relatively little effort now.

**Comment by luongvo** [comment]
@sorccu waiting for your response, I really want this to be available

**Comment by sorccu** [comment]
So, we can build for P now. However, there are some other changes that make life difficult. It seems like the linker is refusing to load symbols from minicap.so, though it can find it:

> adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P 1080x1920@1080x1920/0 -t
> CANNOT LINK EXECUTABLE "/data/local/tmp/minicap-devel/minicap": cannot locate symbol "_Z25minicap_start_thread_poolv" referenced by "/data/local/tmp/minicap-devel/minicap"...

I'm not sure, but this may have something to do with https://source.android.com/devices/architecture/images/vndk_design_android_o.pdf.

Could be that we may have to give up on the shared library and build a separate binary for each arch/sdk combination instead.

**Comment by sorccu** [comment]
Nevermind... I simply forgot to change a few lines and it was referencing an older version. It seems to run fine.

**Comment by sorccu** [comment]
Done

**Comment by varundtsfi** [comment]
Thanks a lot @sorccu

**Comment by thinkhy** [comment]
@sorccu Thanks for your work!

BTW, I just compared the code between minicap_27.cpp and minicap_28.cpp, seems you just made following changes.

```cpp
// minicap_27.cpp: 
277     android::SurfaceComposerClient::openGlobalTransaction();
278     android::SurfaceComposerClient::setDisplaySurface(mVirtualDisplay, mBufferProducer);
279     android::SurfaceComposerClient::setDisplayProjection(mVirtualDisplay,
280       android::DISPLAY_ORIENTATION_0, layerStackRect, visibleRect);
281     android::SurfaceComposerClient::setDisplayLayerStack(mVirtualDisplay, 0); // default stack
282     android::SurfaceComposerClient::closeGlobalTransaction();

// minicap_28.cpp
277     android::SurfaceComposerClient::Transaction t;
278     t.setDisplaySurface(mVirtualDisplay, mBufferProducer);
279     t.setDisplayProjection(mVirtualDisplay,
280       android::DISPLAY_ORIENTATION_0, layerStackRect, visibleRect);
281     t.setDisplayLayerStack(mVirtualDisplay, 0); // default stack
282     t.apply();

```

**Comment by sorccu** [comment]
That is correct. It's more or less what I imagined actually, even a bit simpler since the `Transaction` doesn't inherit from anything. We could have totally done this with `dlsym()`.

We didn't have to touch `setName()` because compiling against the real source allowed the compiler to find and use the real symbol.
