### ISSUE TITLE
documentation for minicap

### ISSUE THREAD

**Issue by pete111** [openstf/minicap#121]
Hi, is documentation for minicap available? I mean arguments such as -Q -P -S etc. I found just usage lines in https://github.com/openstf/minicap/blob/master/jni/minicap/minicap.cpp but no idea what specifically mean e.g. Display projection (4 values  <w>x<h>@<w>x<h>/{0|90|180|270}) or JPEG quality.
Many thanks

**Comment by qmfrederik** [comment]
Did you have a look at the README file? It contains fairly extensive documebtation.

**Comment by pete111** [comment]
thank you I did. Just i was not able to fing something about quality. Is quality JPEG quality generated on device and then sent back via minicap please?

**Comment by sorccu** [comment]
JPEG are generated on the device. Otherwise there would be way too much data to transfer and it would be difficult to get even 1fps.
