### ISSUE TITLE
how you to do to make  devices transfer screenshots just when device's screen change.

### ISSUE THREAD

**Issue by TMLAndroid** [openstf/minicap#123]
how you to do to make  devices transfer screenshots when device's screen change. any doc can i refer . thanks for you replying

**Comment by sorccu** [comment]
Read the README. You detect a rotation event separately and restart minicap. This step is necessary due to the unreliability of the private APIs.

**Comment by TMLAndroid** [comment]
Yes, i had read README. Maybe what I said is not very clear.i mean how to do to make no transfer when device's screen no changed.

**Comment by TMLAndroid** [comment]
Yes,i had read the README. Maybe what I said is not very clear. I mean how to do to make no transfer screenshots when device's screen no change.
I have poor English, thank you for your patience

**Comment by sorccu** [comment]
That's what it does by default, though only on Android 4.3 and later. However, even a small change triggers a new frame. For example, time changing causes the screen to update.

**Comment by TMLAndroid** [comment]
Do you mean that this has been handled internally by Google and we don't need to deal with it separately?
