### ISSUE TITLE
Utilize MediaCodec?

### ISSUE THREAD

**Issue by breeswish** [openstf/minicap#124]
Since Android 5.0, Android has Native MediaCodec. By using a (hardware accelerated) video encoder instead of per-frame Jpeg encoder, I suppose the performance should be better. Ideas?

**Comment by sorccu** [comment]
Feel free to submit a PR. It’s unlikely we’ll make such a big change by ourselves.

**Comment by breeswish** [comment]
Finally comes up with [scrcpy](https://github.com/Genymobile/scrcpy), which contains all useful features I needed. Anyway thanks for your project!
