### ISSUE TITLE
Wrong frames in landscape mode

### ISSUE THREAD

**Issue by lbielski** [openstf/minicap#13]
Hi!

I'm trying to use minicap with my Nexus 4 (api 22)  and I have a problem with frames which I get when the device is rotated into a landscape mode.
I start minicap with the following command:
`LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P 768x1280@384x640/0`

I consume the data with a client written in Java and it works beautifully in portrait mode.
As soon as I rotate the phone into a landscape I get this image:
![minicap_rotated](https://cloud.githubusercontent.com/assets/3857029/11455380/d14b67d4-96b0-11e5-90e9-a0b5357f373c.png)

In my Java client I'm just reading the frame and then decoding it from JPEG using ImageIO.
Is it a decoding issue or rotation is not supported yet?

**Comment by sorccu** [comment]
Just read the README. You need to detect rotation changes with something
and then restart minicap.

**Comment by lbielski** [comment]
Thanks for the answer!

Actually I read the readme (otherwise I wouldn't be able to implement a client), and it says that if I'm in `always upright` quirk mode I should take it into account while rendering: "This needs to be taken into account when rendering the image."

So I assumed that I should get a rotated landscape image and then rotate it while rendering.

Any suggestions how I can detect the rotation changes?

**Comment by sorccu** [comment]
If the quirks flags say the device has QUIRK_ALWAYS_UPRIGHT, then it means that when rotation is 0 or 180, you get a portrait image that's never upside down, or if rotation is 90 or 270, a landscape image that's never upside down.

You can try [RotationWatcher.apk](https://github.com/openstf/RotationWatcher.apk) like mentioned in the README.

**Comment by sorccu** [comment]
Also, I know it sounds stupid that you have to do it that way, but it's due to limitations of the private APIs.

**Comment by lbielski** [comment]
I'm so sorry - missed that portion of the README :(
Now everything is clear.
Thanks for your help!
