### ISSUE TITLE
Image scale by minicap is not smooth

### ISSUE THREAD

**Issue by alexazhou** [openstf/minicap#130]
Hope that minicap can use a better image scaling algorithm.

Detail:
-------
This phone screen size is 1080*1920. we can see that mac preview scale output is much better then minicap 

### Image A: minicap output at 1080*1920:
![1080x1920](https://user-images.githubusercontent.com/9353779/39812880-f0679d48-53c0-11e8-920e-894820b40e69.jpg)

### Image B: minicap output at 360*640:
![360x640_scale_by_minicap](https://user-images.githubusercontent.com/9353779/39812888-fad5b738-53c0-11e8-880a-938bd90e24d0.jpg)

### Image C: Use mac preview app open Image A and save it as 360*640:
![360x640_scale_by_mac_preview](https://user-images.githubusercontent.com/9353779/39812944-2a9c1d36-53c1-11e8-85fd-daa258510e6b.jpg)

**Comment by sorccu** [comment]
You can capture at a larger size and scale it down yourself. Minicap doesn’t actually scale the age directly. It asks SurfaceFlinger to project a smaller size, so it’s up to SurfaceFlinger.

You can try to play with the jpg encoding parameters in JpegEncoder.cpp for possible small gains, though. Try increasing the quality, for example.

**Comment by alexazhou** [comment]
I had try to set the output to a large size before, but large image need more transfer time make the system slow 😓.  So I hope minicap can offer a good quality at small size, that will be very good.

Thank you any way, I will set minicap to a large size and scale it myself
