### ISSUE TITLE
Adapt the P version of minicap

### ISSUE THREAD

**Issue by lulu017** [openstf/minicap#132]
**What is the issue or idea you have?**

Hello, I want to adapt the P version of minicap for some needs.
May I ask what aspects of code I need to pay attention to?
Thank you very much for your help.

**Comment by sorccu** [comment]
Follow the build instructions and build against the latest android-p-preview AOSP branch. You'll get it to compile fairly easily. Then run it on an actual device and it'll complain about missing symbols. You take it from there.

**Comment by lulu017** [comment]
Thank you very much.
I'm still a novice, and if I have other problems that can't be solved, I expect to continue asking for help.
