### ISSUE TITLE
Could i get fullscreen pixels no matter what rotation it is?

### ISSUE THREAD

**Issue by BeiKeJieDeLiuLangMao** [openstf/minicap#133]
**What is the issue or idea you have?**
I feel it speeding too many time, if i detect rotation change event, then restart minicap with correct parameters.
Is that possible to create a 1920*1920 virtual display(If device resolution is 1080*1920), then client receives this 1920*1920 image and clips it to correct resolution, like 1080*1920 or 1920*1080?
I amn't sure about the possibility of this idea.

**Comment by sorccu** [comment]
No, because you have to tell it which projection you want to use. Think of the entire output image as one canvas (or outer canvas). We have to assign a specific area within that canvas to be the area we project to. Think of that as the inner canvas. So even though you can make the outer canvas square, the inner canvas cannot be square because the image would get stretched to fill the whole inner canvas.

**Comment by BeiKeJieDeLiuLangMao** [comment]
I try to set a square resolution, like realWidth=2220, realHeight=2220, virtualWidth=850, virtualHeight=850, i don't restart minicap then rotation changed and i get these images:
![1530524354973](https://user-images.githubusercontent.com/13994321/42156960-03b7474e-7e1f-11e8-9d22-1cfef03b436a.jpg)
![1530524472226](https://user-images.githubusercontent.com/13994321/42156995-222b50c6-7e1f-11e8-839d-72834ea13323.jpg)
I am not sure is that a coincidence? Or maybe all kinds of android versions' devices will performance same?

**Comment by sorccu** [comment]
It might depend on the device. Some will scale the image, some won't. Regardless, you have provided a useful data point. What device were you using?

**Comment by BeiKeJieDeLiuLangMao** [comment]
The device which i got previous pictures from is Samsung Note8, by the way, my others device performance same like it, eg: XiaoMi 8, Samsung G3589W ...

**Comment by BeiKeJieDeLiuLangMao** [comment]
@sorccu 
https://github.com/BeiKeJieDeLiuLangMao/minicap
This is my minicap edition, normally i set real width/height and virtual width/height to be 1920(in 1080x1920 device), and i add some new parameters, named image width/height.If stf agent emits a rotation event, i will reset image width/height by socket, like 1080x1920=>1920x1080.
In this way, i needn't restart minicap on rotation happened, i only need reset image parameters, and then next image will be right.
If you are Interested in this solution, maybe you could take a look, and try it in your devices.

**Comment by sorccu** [comment]
I think it needs a lot of testing on various Android versions and devices, SurfaceFlinger is one of those things that can behave in a very odd way on different devices.
