### ISSUE TITLE
Some black border in minicap image.....

### ISSUE THREAD

**Issue by scucsxn** [openstf/minicap#138]
![1537512840](https://user-images.githubusercontent.com/10509715/45864915-4edf0d00-bdae-11e8-9640-d5d6eda2f232.png)

when I killed minicap and restarted it ,it work well...but sometimes it work not well

**Comment by sorccu** [comment]
Incorrect parameters probably.

**Comment by scucsxn** [comment]
with and height is 75%, black border is 25%

**Comment by scucsxn** [comment]
which prameters?
