### ISSUE TITLE
minicap crash!!

### ISSUE THREAD

**Issue by scucsxn** [openstf/minicap#139]
when I invoke the function of applyConfigChanges on android 8.0, minicap crashed. but on android 5.0, 6.0 ,it works well.

**Comment by sorccu** [comment]
Minicap works fine on Android 8.0, it's not an issue with the Android version. However, some devices might not work. You should let us know which device you're trying to use.

**Comment by scucsxn** [comment]
I know your means, samsung galaxy s8,  my devies are all SM in clude 5.0, 6.0, 7.0, 8.0.........when the screeen rotated, for screen shot, I invoke applyConfigChanges
