### ISSUE TITLE
Black part in jpeg

### ISSUE THREAD

**Issue by umutuzgur** [openstf/minicap#14]
Hi guys. I ran into an issue today. I ran the script with these arguments -P 1280x1920@640x960/0 on LG G2. The the global header said that it is 960 but then I got this image which was weird. I encountered this with my java client, then tried the example app and also got the same image. I don't get this when I project the real size of the phone. Any ideas?
<img width="642" alt="screen shot 2015-12-20 at 21 21 52" src="https://cloud.githubusercontent.com/assets/5844182/11919918/ce3ba4f4-a75f-11e5-968a-ea936ae4650d.png">

**Comment by umutuzgur** [comment]
Sorry, my bad. I realised that I entered some wrong values.

**Comment by sorccu** [comment]
Yeah, looks like the true original size is actually 1080x1920 :)
