### ISSUE TITLE
Can the server directly link to minicap rather than Local port forwarding

### ISSUE THREAD

**Issue by fenggandejiangnan** [openstf/minicap#141]
I mean the server directly connects to the minicap service on the android device for file transfer, not the usb interface，is ok? what to do ？thanks a lot

**Comment by sorccu** [comment]
No, that is not supported.

**Comment by fenggandejiangnan** [comment]
thanks a lot，It would be perfect if it was compatible

**Comment by fenggandejiangnan** [comment]
If we want the server to connect the phone remotely, can we open a socket on the phone, listen to the minicap server, and upload the receipt to our server back end?
