### ISSUE TITLE
Can't install minicap Android NDK: APP_STL gnustl_static is no longer supported

### ISSUE THREAD

**Issue by Katsuyu** [openstf/minicap#148]
When trying to install minicap, the installation stopped with this error message : 
```
~/virtual-mobile-devices/server/dependencies/minicap ~/virtual-mobile-devices/server
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
/home/Katsu/virtual-mobile-devices/server/dependencies/android_sdk/ndk-bundle/build/core/add-application.mk:178: *** Android NDK: APP_STL gnustl_static is no longer supported. Please switch to either c++_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop.
error while installing  minicap , aborting..;
```
Do you plan to support / fix that in the future ?  Do you have any idea on how to avoid this ?

**Comment by sorccu** [comment]
Use an older NDK or do the change yourself for now. It’s quite easy.

**Comment by luxuecom** [comment]
Google the problem and fix it.
In the jni/Application.mk file,  just add/modify the following:
APP_PLATFORM := android-21
APP_STL := c++_static

**Comment by fablexis** [comment]
@luxuecom when doing what you said I got this when making `ndk-build`:

`make: *** No rule to make target '/Users/fpernia/Documents/minicap/jni/minicap-shared/mock/Minicap.cpp', needed by 'obj/local/armeabi-v7a/objs/minicap-shared/mock/Minicap.o'.  Stop.`

So it does not work...
