### ISSUE TITLE
Does possible install minicap on device ,then connect minicap with wireless local network pc?

### ISSUE THREAD

**Issue by vanshu** [openstf/minicap#151]
**What is the issue or idea you have?**
Can I install minicap on the device, then connect minicap with a wireless local network pc?

adb forward tcp:1717 localabstract: minicap,
adb forward command transfer cellphone port to local pc, is there any command set up minicap and connect with the same network wireless machine?

**Comment by guowee** [comment]
yes ! I've done it.  Don't need to run "adb forward tcp:1717 ";  just start a TCP server, then connect it by client directly in local area network.
