### ISSUE TITLE
where is turbojpeg.h

### ISSUE THREAD

**Issue by JabariDuan** [openstf/minicap#16]
when i execution ./run.sh -P 720x1280@720x1280/0 as the README.md in the example folder

it report back：
        In file included from jni/minicap/JpgEncoder.cpp:3:0:
        jni/minicap/JpgEncoder.hpp:4:23: fatal error: turbojpeg.h: No such file or directory
        #include <turbojpeg.h>

I realized that i need the libjpeg-turbo 

but how did i use it ? just down and make it or the other way?

I saw the prompt that  “We include [libjpeg-turbo as  a Git submodule](https://github.com/openstf/android-libjpeg-turbo), so first make sure you've fetched it.”

but i did not understand.
I am a novice. please help me
thank you

**Comment by sorccu** [comment]
Yeah, you need to fetch the submodules.

https://git-scm.com/book/en/v2/Git-Tools-Submodules#Cloning-a-Project-with-Submodules

**Comment by JabariDuan** [comment]
Thanks for your help!
