### ISSUE TITLE
MiniCap hangs on start

### ISSUE THREAD

**Issue by stoefln** [openstf/minicap#166]
**What is the issue or idea you have?**
Sometimes when launching minicap, it just stops after 
`INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder`

My start command: 
`adb -s ce12160c426ed42f04 shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -Q 100 -P 1440x2560@1440x2560/0$@`

Full output:
```
PID: 30206
INFO: Using projection 1440x2560@1440x2560/0
INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_26.cpp:264) Setting buffer options
INFO: (external/MY_minicap/src/minicap_26.cpp:268) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_26.cpp:272) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_26.cpp:276) Publishing virtual display
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder
```

Some other times it finishes with 
`INFO: (external/MY_minicap/src/minicap_26.cpp:291) Destroying virtual display`

This happens for me on emulators and real devices.

**MiniCap Version**
v2.3.0

**Have you tried STF?**
I am sorry, STF seems like a big effort to set up. I am just using MiniCap by itself.

**Comment by sorccu** [comment]
Try STF. It may be some effort for you but surely you understand that it’s more effort for me to support you if you don’t do that. Seems a bit unfair.

I’m thinking you’re just not consuming the frames.

**Comment by stoefln** [comment]
@sorccu yes, you are right- I already looked at how STF does it- I am pretty sure its working there. Couldn't find a difference so far. But thanks for your assessment!
