### ISSUE TITLE
How to use the android-libjpeg-turbo

### ISSUE THREAD

**Issue by JabariDuan** [openstf/minicap#17]
I have git submodule add https://github.com/openstf/android-libjpeg-turbo
and saw the android-libjpeg-turbo in the minicap-master 

but it still report me that “jni/minicap/JpgEncoder.hpp:4:23: fatal error: turbojpeg.h: No such file or directory” when i ndk-build

What is wrong or forget to do

**Comment by sorccu** [comment]
You are doing it wrong, that's now how you fetch submodules. I gave you a link last time to the exact 2 commands you need to run.

**Comment by JabariDuan** [comment]
I succeeded.
thank you.
