### ISSUE TITLE
doesn't work in apk

### ISSUE THREAD

**Issue by SheilaLundin** [openstf/minicap#172]
**What is the issue or idea you have?**
I built a shared library minicap instead of the executable version, and packed it into an apk.  It didn't work. Here is the error log.
`Unable to start minicap with current config`
However, when I loaded the library from an executable file, then ran it in android shell, it worked well.

**Comment by sorccu** [comment]
It won’t work like that. The shell user has different permissions that allow it to run. Use the public virtual display APIs instead.
