### ISSUE TITLE
My App wants to get data from minicap

### ISSUE THREAD

**Issue by theosu** [openstf/minicap#188]
**What is the issue or idea you have?**

**Have you tried STF?**

My App has shell permissions;And my app want to collect data that minicap produced;
how can i do that?thanks

**Comment by sorccu** [comment]
Read the README. Use any language you want.

**Comment by theosu** [comment]
I have seen the ReadME;
It told me that I hava to use the adb forward command so that I can get data in my PC
But my app is in the same phone that minicap execuated. So i can not use adb forward command;
If there is any other way I can get data from minicap?

**Comment by sorccu** [comment]
No. Can’t be done due to permissions.

You should look at using the public virtual display APIs instead.

**Comment by theosu** [comment]
Thanks for the reply; I have the shell permissions because I use adblib:https://github.com/cgutman/AdbLib
My question is : can I connect to minicap simply by socket?
