### ISSUE TITLE
MinicapINFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder

### ISSUE THREAD

**Issue by kavithamanivel** [openstf/minicap#194]
Hi,

I tried openstf locally using ONEPLUS 5T. Its working fine. But when i use this Minicap project separately with same device ONEPLUS 5T, iam getting this error "INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 2766852 bytes for JPG encoder"

**Comment by koral--** [comment]
`INFO` it does not look like an error. Please post more output.

**Comment by kavithamanivel** [comment]
True. Got fixed. Thank you
