### ISSUE TITLE
compile the minicap.so

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minicap#20]
Because of my C disk does not have enough space for aosp, so I have downloaded it into home/srv/aosp directory. Now I try to run the docker command directly, such as: "docker run --rm -a stdout -a stderr -v /home/srv/aosp/android-5.1.0_r1:/aosp -v /tmp/minicap/:/app -v /tmp/minicap/libs/android-22/x86:/artifacts openstf/aosp:jdk7 /aosp.sh build generic-eng minicap". This command means I want to compile the x86 file, but it brought out the armeabi-v7a file. So, how can I build the x86 file, could you give me some suggestions. Thx.

**Comment by sorccu** [comment]
See https://github.com/openstf/minicap/blob/master/jni/minicap-shared/aosp/Makefile.

**Comment by likezjuisee** [comment]
If I have modified the file under the "https://github.com/openstf/minicap/tree/master/jni/minicap-shared/aosp/src" folder, how can I build the new file. I did not see the file info in the docker commands.

**Comment by sorccu** [comment]
You rebuild with the same command. Like the docs say rebuilding will be faster, but no super fast. It's not ideal.
