### ISSUE TITLE
how to get minicap.so for android-29

### ISSUE THREAD

**Issue by wliruohan** [openstf/minicap#200]
**What is the issue or idea you have?**
HI,
I am trying to use minicap for my platform with the following parameters:
D:\adb\adb>adb shell getprop ro.product.cpu.abi
armeabi-v7a

D:\adb\adb>adb shell getprop ro.build.version.sdk
29

I found the minicap for the armeabi-v7a, but not found minicap.so for sdk29. Do the minicap apply to the android 29 ,  which maybe we called android Q.

Looking foraward to your reply.

Thank you so much !
Ronan 
**Have you tried STF?**

**Comment by koral--** [comment]
Here is a PR for API 29 support: https://github.com/openstf/minicap/pull/190
