### ISSUE TITLE
checkout branch

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minicap#21]
The other branches are downloaded successfully, but the android-5.0.1_r1 is failed. The error info is:

 [root@localhost /]# docker run -ti --rm -v /home/srv/aosp/mirror:/mirror -v /home/srv/aosp/android-5.0.1_r1:/aosp -v $PWD/.gitcookies:/root/.gitcookies:ro openstf/aosp:jdk7 /aosp.sh checkout-branch android-5.0.1_r1
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
error: command 'sync' requires repo to be installed first.
         Use "repo init" to install it here.

**Comment by sorccu** [comment]
Can't help you with that, it works fine on my Arch Linux machine. If you're using a VM, it sounds like it isn't happy with the way you're sharing the AOSP source code folder between your machine and the VM.
