### ISSUE TITLE
minicap can't start normally

### ISSUE THREAD

**Issue by yftyxa** [openstf/minicap#212]
**C:\NDK\minicap>adb shell getprop ro.product.cpu.abi
arm64-v8a
C:\NDK\minicap>adb shell getprop ro.build.version.sdk
25**

after ndk-build, i push minicap and minicap.so to /data/local/tmp, also, chmod 777 to them, however, when i lunch minicap, only two info displayed:
**PID: 24461
INFO: Using projection 720x1280@720x1280/0**

and i didn't catch any log, pls help fix this problem,thx

**Comment by koral--** [comment]
What is the device model?

**Comment by yftyxa** [comment]
### C:\Users\win10>adb shell getprop ro.product.model
cloudphone
it is a cloud service，i successed two days ago，but now it doesn't work

**Comment by EdwardCheck** [comment]
> What is the device model?

Have you tried Xiaomi 10 ( rom version MIUI 11) , SDK = 29  ? 

adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x3120@1440x3120/0

**Vector<> have different types (this=0x7fdf71d010, rhs=0x7fdf71d130)
Aborted**

I also tried Huawei, the sdk version is also 29,it can work OK

**Comment by varundtsfi** [comment]
- Please refer two already running threads #169 and #190

**Comment by yftyxa** [comment]
i have fixed this problem，thx all

**Comment by caixiyan** [comment]
@yftyxa Can you share the compiled package, thank you.My MIUI11 also has this problem.The package I use in #169 and #190, minicap can start, but the screen is black. So I want to try the package you compiled.

**Comment by yiqingkuang** [comment]
> 我已经解决了这个问题，谢谢所有

Hello, I encountered the same problem as you, how did you solve it in the end, I look forward to your reply

**Comment by milankmr** [comment]
Hello, I am facing the same issue , how did you solve ? can you please share ?
