### ISSUE TITLE
ndk-build does not affect new code (modified "minicap-shared")

### ISSUE THREAD

**Issue by nhunh585** [openstf/minicap#215]
I modified minicap-shared to change the log output then run ndk-build, then I use new minicap, minicap.so but the log still same old version.

**Comment by varundtsfi** [comment]
You have to build the cpp file with android os then you can change the logs. With ndk -build it's taking only already builded minicap.so file which is in aosp directory.

**Comment by nhunh585** [comment]
Hi @varundtsfi Is what you say in this page ?https://github.com/openstf/minicap/blob/master/jni/minicap-shared/README.md

**Comment by varundtsfi** [comment]
Yes correct.

**Comment by nhunh585** [comment]
@varundtsfi Thank you

**Comment by koral--** [comment]
It seems that there is an answer so closing this ticket.

**Comment by nhunh585** [comment]
@varundtsfi 
I ran `make` in the folder `minicap/jni/minicap-shared/aosp` and there is an error. Do you know how to fix it ?

![image](https://user-images.githubusercontent.com/25640067/83862856-b688e780-a74c-11ea-936c-91826d813660.png)

**Comment by nhunh585** [comment]
Here is full log of `make` command

`make -j 2
mkdir -p libs/android-28/x86_64
docker run --rm \
                -a stdout -a stderr \
                -v /Volumes/android/android-9.0.0_r1:/aosp \
                -v /Users/nhunh/workspace/source/minicap/jni/minicap-shared/aosp/:/app \
                -v /Users/nhunh/workspace/source/minicap/jni/minicap-shared/aosp/libs/android-28/x86_64:/artifacts \
                openstf/aosp:jdk8 /aosp.sh build aosp_x86_64-eng minicap
including device/generic/car/vendorsetup.sh
including device/generic/mini-emulator-arm64/vendorsetup.sh
including device/generic/mini-emulator-armv7-a-neon/vendorsetup.sh
including device/generic/mini-emulator-mips/vendorsetup.sh
including device/generic/mini-emulator-mips64/vendorsetup.sh
including device/generic/mini-emulator-x86/vendorsetup.sh
including device/generic/mini-emulator-x86_64/vendorsetup.sh
including device/generic/uml/vendorsetup.sh
including device/google/cuttlefish/vendorsetup.sh
including device/google/marlin/vendorsetup.sh
including device/google/muskie/vendorsetup.sh
including device/google/taimen/vendorsetup.sh
including device/linaro/hikey/vendorsetup.sh
including sdk/bash_completion/adb.bash

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_x86_64
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86_64
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.76-linuxkit-x86_64-Ubuntu-16.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PPR1.180610.009
OUT_DIR=out
============================================
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=aosp_x86_64
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86_64
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.19.76-linuxkit-x86_64-Ubuntu-16.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PPR1.180610.009
OUT_DIR=out
============================================
[1/1] out/soong/.minibootstrap/minibp out/soong/.bootstrap/build.ninja

[1/1] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja 
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -o out/soong/build.ninja Android.bp
Killed
ninja: build stopped: subcommand failed.
09:47:55 soong bootstrap failed with: exit status 1
make: *** [libs/android-28/x86_64/minicap.so] Error 1`
