### ISSUE TITLE
can't runing ....

### ISSUE THREAD

**Issue by workzj** [openstf/minicap#22]
i build on windows7 use NDKR10D and AOSP is android 4.4 

the code like this : 

    android::sp<android::SurfaceComposerClient> sc = new android::SurfaceComposerClient();
    if ((err = sc->initCheck()) != android::NO_ERROR) {
      MCERROR("Unable to initialize SurfaceComposerClient");
      return err;
    }

all ways return  error , why ? i checked the android4.4 source , and class SurfaceComposerClient:

SurfaceComposerClient::SurfaceComposerClient()
    : mStatus(NO_INIT), mComposer(Composer::getInstance())
{
}

status_t SurfaceComposerClient::initCheck() const {
    return mStatus;
}

the code means , initCheck is allways return NO_INIT .

**Comment by sorccu** [comment]
I don't know, maybe the Android.mk files behave a bit differently on Windows and something breaks. I only build on Linux, so I can't help you. If you get it working, please submit a patch.

Also, you said that you're always getting an error, but didn't actually post the error.

**Comment by workzj** [comment]
i means , view the code , when you new SurfaceComposerClient , mStatus is set NO_INIT ,
BUT immediately the code : sc->initCheck(); check mStatus is not NO_ERROR, so the code is always return err;

**Comment by sorccu** [comment]
```cpp
void SurfaceComposerClient::onFirstRef() {
    sp<ISurfaceComposer> sm(ComposerService::getComposerService());
    if (sm != 0) {
        sp<ISurfaceComposerClient> conn = sm->createConnection();
        if (conn != 0) {
            mClient = conn;
            mStatus = NO_ERROR;
        }
    }
}
```

This is magic that gets called before we call `initCheck()`.
