### ISSUE TITLE
The error about building android 23 version

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minicap#24]
make: *** No rule to make target `out/target/product/generic/obj/STATIC_LIBRARIES/libunwind_llvm_intermediates/export_includes', needed by `out/target/product/generic/obj/SHARED_LIBRARIES/minicap_intermediates/import_includes'.  Stop.

**Comment by sorccu** [comment]
Not sure about this one it has always worked for me. However I just updated the build for SDK 23 so who knows, maybe your issue is solved now?
