### ISSUE TITLE
what is the possible reason of " Unable to initialize SurfaceComposerClient " ?

### ISSUE THREAD

**Issue by workzj** [openstf/minicap#26]
my jni code : 

android::sp<android::SurfaceComposerClient> sc = new android::SurfaceComposerClient();

is failed .

i don't know why ?? 
look up the android source , i wirte the test code like this : 

	//test code
	sp<ISurfaceComposer> sm(ComposerService::getComposerService());
	if (sm != 0) {
		sp<ISurfaceComposerClient> conn = sm->createConnection();
		if (conn != 0) {
			LOG("init success ... ");
			return 1;
		}
		LOG("conn == 0");
		return -1;
	}
 
the run result is : conn == 0 . 
my question is why createConnection is failed ?
is authority ? is thread ?

###
i use the code in apk with JNI .

**Comment by sorccu** [comment]
Normal applications don't have permission to access SurfaceComposerClient. Only system apps can do it, or you can try rooting your device. Alternatively, if you're OK with supporting only Android 5.0+, try adding the `CAPTURE_VIDEO_OUTPUT` permission. I haven't tried it myself but it might work. Although if you're OK with 5.0+, you should use the official public APIs instead.

**Comment by workzj** [comment]
but,my device is root . and i run app on android 4.4. is any other reason?

**Comment by sorccu** [comment]
Does your app run as root?

**Comment by workzj** [comment]
yes,
JNIEXPORT jint JNICALL Java_com_hupo_Screenshot(JNIEnv *jPE, jobject jo, jint jiX, jint jiY)
{

	int result = system("su");
	if (result == -1)
	{
		return -1;
	}

	ProcessState::self()->startThreadPool();

	ScreenshotClient mScreenshotClient;
	
	sp<android::CpuConsumer> mConsumer;
	sp<android::IBinder> mVirtualDisplay;
	CpuConsumer::LockedBuffer mBuffer;
	sp<FrameProxy> mFrameProxy;
	status_t err;

	DisplayInfo dinfo;
	/*
	sp<android::IBinder> dpy = SurfaceComposerClient::getBuiltInDisplay(DEFAULT_DISPLAY_ID);
	err = SurfaceComposerClient::getDisplayInfo(dpy, &dinfo);

	if (err != NO_ERROR) {
		LOGD("SurfaceComposerClient::getDisplayInfo() failed: %s (%d)\n", error_name(err), err);
		return err;
	}*/

	//test code
	sp<ISurfaceComposer> sm(ComposerService::getComposerService());
	if (sm != 0) {
		sp<IBinder> dtoken(SurfaceComposerClient::getBuiltInDisplay(ISurfaceComposer::eDisplayIdMain));

		status_t err = sm->captureScreen(dtoken, mBufferQueue,800, 1024, 0, -1UL);

		sp<ISurfaceComposerClient> conn = sm->createConnection();
		if (conn != 0) {
			LOG("init success ... ");
			return 1;
		}
		LOG("conn == 0");
		return -1;
	}

	return -1;
}

**Comment by sorccu** [comment]
That's not how `su` works... you only get root permissions inside su's child processes. Your code doesn't do anything.

**Comment by sorccu** [comment]
Also what does this have to do with minicap?

**Comment by workzj** [comment]
this is my test code , because of my original code : 
	// Create a Surface for the virtual display to write to.
	LOG("Creating SurfaceComposerClient");
	android::sp<android::SurfaceComposerClient> sc = new android::SurfaceComposerClient();

	LOG("Performing SurfaceComposerClient init check");
	if ((err = sc->initCheck()) != android::NO_ERROR) {
		LOGD("Unable to initialize SurfaceComposerClient failed: %s (%d)", error_name(err), err);
		return err;
	}

 is " Unable to initialize SurfaceComposerClient ".so i write this test.

**Comment by sorccu** [comment]
I see. Well, you need to fix your su usage somehow, but if you get that fixed I think it will work.

**Comment by workzj** [comment]
i don't understand ... you means , my app has not get the root authority ?

**Comment by sorccu** [comment]
Yes, because that's not how `su` works.

**Comment by workzj** [comment]
thank you ~!  i try
