### ISSUE TITLE
Use inside app without adb

### ISSUE THREAD

**Issue by RPallas92** [openstf/minicap#30]
Is it possible to include minicap in an .apk and use it without adb?
Maybe creating a websocket server inside de apk with nanohttpd? Any suggestions?
Thank you

**Comment by sorccu** [comment]
No, normal applications don't have access to the necessary permissions. I
would look into using the official VirtualDisplay API instead.

**Comment by RPallas92** [comment]
And if the device is rooted?

Now I'm taking screenshots with screencap command


    private static void takeScreenshot(){
        try {
            Process sh = Runtime.getRuntime().exec("su", null,null);
            OutputStream os = sh.getOutputStream();
            os.write(("/system/bin/screencap -p " + "/sdcard/img.png").getBytes("ASCII"));
            os.flush();
            os.close();
            sh.waitFor();
        } catch (Exception ex){
            ex.printStackTrace();
        }

    }


reading it, converting to base64, and send to the client via websockets every 200ms

But it's very very slow

**Comment by sorccu** [comment]
If it's rooted you can do whatever you want.

**Comment by RPallas92** [comment]
I end up using MediaRecorder, and sending the images as bytes arrays through websockets to the web app. It works smoothly. Thanks

**Comment by txchen** [comment]
@RPallas92 do you mind sharing more details about your final solution? Is mediaRecorder working on api 19 or api 18? If you can share some key source code, that will be wonderful. Thanks a lot!
