### ISSUE TITLE
Minicap Stream Orientation

### ISSUE THREAD

**Issue by haihaoshen** [openstf/minicap#33]
Hi,

I can run the example following the sample instructions. However, I found there is one issue that the command orientation is hard code for the first run minicap binary. Sometimes, Android app 1 launches at Landscape while app 2 launches at Portrait. Is there any way to make it adapt automatically?

adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@1440x2560/0 (0 Portrait)

Thanks,
Harry

**Comment by sorccu** [comment]
The README covers that. You need to use another utility, which you can make on your own, to detect rotation changes. Then you restart minicap with the correct parameters.

**Comment by haihaoshen** [comment]
thanks.

**Comment by sorccu** [comment]
It's because it's not possible to do it within minicap for all the API levels it supports.
