### ISSUE TITLE
Is it possible to send smartphone realtime audio to pc web?

### ISSUE THREAD

**Issue by ymifa** [openstf/minicap#36]
When I test apps in stf with browser, there is only realtime screen image seen in browser. Is it possible to send smartphone realtime audio as well as screen ?

**Comment by vbanthia** [comment]
There is already an issue for this feature, https://github.com/openstf/stf/issues/22

**Comment by slakshmiumesh1** [comment]
Is this issue fixed and what is the resolution?

**Comment by sorccu** [comment]
It is not. Minicap doesn't handle audio.
