### ISSUE TITLE
adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P x@x/0 /system/bin/sh: /data/local/tmp/minicap-devel/minicap: can't execute: Permission denied

### ISSUE THREAD

**Issue by prithiviraj** [openstf/minicap#37]
cant access permission denied

**Comment by sorccu** [comment]
You have to mention which device you're using or it's impossible to say anything.

**Comment by prithiviraj** [comment]
nexus 5

**Comment by sorccu** [comment]
And which version of Android? Please don't make me ask every single detail, that's just wasting my time.

**Comment by prithiviraj** [comment]
i have tried in nexus5 version 6.0.1 and Samsung Galaxy Young Duos S6312, android version 4.1.2 same problem, cant access permission denied

**Comment by sorccu** [comment]
Nexus 5 on 6.0.1 works fine. I think the issue is something else. Did you use the `./run.sh` script?

**Comment by prithiviraj** [comment]
yes starting the minicap im using this command ./run.sh autosize

**Comment by sorccu** [comment]
Which OS do you use? And which version?

**Comment by prithiviraj** [comment]
windows 10 pro version 1511 and im trying using Cygwin64 Terminal

**Comment by sorccu** [comment]
I never develop on Windows and will therefore not be able to check the issue. I would recommend creating a Linux VM and building from there. If you manage to figure out what's wrong, a PR is welcome. Sounds like the executable flags are not getting set correctly but who knows.

**Comment by serezhka** [comment]
@prithiviraj , try to add 
" adb shell chmod 0755 $dir/$bin " after " adb push .. "

**Comment by prithiviraj** [comment]
@serezhka, i tried same problem permission denied

**Comment by thulasipavankumar** [comment]
@prithiviraj 
I too faced the same issue follow the below mentioned steps to overcome the issue 
Execute  the following commands in command prompt
-> adb -s "deviceid" shell              ( this will enter  to the device adb shell)
-> cd /data/local/tmp/                    ( assuming you pushed minicap to /data/local/tmp/ )
-> chmod 777 minicap

**Comment by sorccu** [comment]
Perhaps https://github.com/openstf/stf/issues/436 is of interest to you. Current STF installs to `/data/data/com.android.shell` if `/data/local/tmp` doesn't work.

**Comment by sreenivash** [comment]
**Minicap Working in windows**
Manually execute the following command in command line
-- adb shell "mkdir /data/local/tmp/minicap-devel 2>/dev/null || true" 
-- adb push libs/_<your_device_acrhitecture>_/minicap /data/local/tmp/minicap-devel
-- adb push jni/minicap-shared/aosp/libs/android-_<Android_OS_API_verion>_/<your_device_acrhitecture>/minicap.so /data/local/tmp/minicap-devel
-- adb shell chmod 777 /data/local/tmp/minicap-devel/minicap -> _execute this command in **CYGWIN**_
-- adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap run.sh -P _<Deivce_Resolution>@<Projection_Resoultion>/<ScreenRotation>_

**Comment by Restry** [comment]
fix it 

`adb shell chmod 777 /data/local/tmp/minicap-devel/minicap
`

**Comment by oujibahei** [comment]
Even after execute ```adb shell chmod 777 /data/local/tmp/minicap-devel/minicap``` still gets the 'permission denied' notice on Windows.
