### ISSUE TITLE
how can i change the port when i start the minicap socke server ?

### ISSUE THREAD

**Issue by fengzhou** [openstf/minicap#38]

**Comment by sorccu** [comment]
Run minicap with the `-h` flag and it will tell you.

**Comment by fengzhou** [comment]
thanks i will try.

**Comment by fengzhou** [comment]
C:\Users>adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -h
Usage: /data/local/tmp/minicap [-h] [-n <name>]
  -d <id>:       Display ID. (0)
  -n <name>:     Change the name of the abtract unix domain socket. (minicap)
  -P <value>:    Display projection (<w>x<h>@<w>x<h>/{0|90|180|270}).
  -s:            Take a screenshot and output it to stdout. Needs -P.
  -S:            Skip frames when they cannot be consumed quickly enough.
  -t:            Attempt to get the capture method running, then exit.
  -i:            Get display information in JSON format. May segfault.
  -h:            Show help

don't get the message of change the minicap port . the name ?

**Comment by sorccu** [comment]
There is no port. There's an abstract unix socket and the name of it can be seen in the help message.

**Comment by fengzhou** [comment]
i got many mobile phone. and just one pc.
i want to use minicap to get those phones's screen . could you please give me a way .

**Comment by sorccu** [comment]
Use [STF](https://github.com/openstf/stf) or figure it out yourself. Aside from the README, we don't help with usage.

**Comment by fengzhou** [comment]
i had installed stf .and it working now.
and i want to know the minicap in the stf. How to achieve a computer to get a number of mobile phone screen。
the openstf/minicap/example/app.js .i just run once node app.js .when i run another node app.js  ,it don't work . by the port 9002 .

**Comment by sorccu** [comment]
The example is not a full blown app. You're asking for too much, we don't provide that level of support. You can take a look at the STF source to see how it does it.
