### ISSUE TITLE
Can i host on another android phone?

### ISSUE THREAD

**Issue by amitg2291632** [openstf/minicap#4]
Hi,

Can i run node app.js on same  android device   ?
I am able to do run node on device but when i am running example/app.js on same device its giving error "adb forward tcp:1717 localabstract:minicap"

So my main issue is i cant do adb forward because i am running on same device,
So is this possible to get jpeg data on same device ?

Let me know for any more information Please help.

Thanks in advance

Regards,
Amit Garg

**Comment by sorccu** [comment]
You'd have to do the forward some other way. I think it's going to be difficult without rooting your device.

**Comment by amitg2291632** [comment]
my device is rooted :)

**Comment by sorccu** [comment]
You could perhaps use `socat` or something similar for the forward. I can't help with this, but if you find a way, please post it here!
