### ISSUE TITLE
Run "run.sh" exception

### ISSUE THREAD

**Issue by xiaowuming** [openstf/minicap#43]
$ ./run.sh -h for help
+ ndk-build NDK_DEBUG=1
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : libs/armeabi-v7a/gdb.setup
[arm64-v8a] Gdbserver      : [aarch64-linux-android-4.9] libs/arm64-v8a/gdbserver
[arm64-v8a] Gdbsetup       : libs/arm64-v8a/gdb.setup
[x86] Gdbserver      : [x86-4.9] libs/x86/gdbserver
[x86] Gdbsetup       : libs/x86/gdb.setup
[x86_64] Gdbserver      : [x86_64-4.9] libs/x86_64/gdbserver
[x86_64] Gdbsetup       : libs/x86_64/gdb.setup
[armeabi-v7a] Compile++ thumb: minicap-common <= JpgEncoder.cpp
In file included from jni/minicap/JpgEncoder.cpp:3:0:
jni/minicap/JpgEncoder.hpp:4:23: fatal error: turbojpeg.h: No such file or directory
 #include <turbojpeg.h>
                       ^
compilation terminated.
/usr/src/ndk/build/core/build-binary.mk:499: recipe for target 'obj/local/armeabi-v7a/objs-debug/minicap-common/JpgEncoder.o' failed
make: *** [obj/local/armeabi-v7a/objs-debug/minicap-common/JpgEncoder.o] Error 1

**Comment by sorccu** [comment]
Did you fetch git submodules?

**Comment by xiaowuming** [comment]
Has been resolved, thank you
