### ISSUE TITLE
Segmentation fault  when running minicap in SAMSUNG Galaxy note4

### ISSUE THREAD

**Issue by willysys** [openstf/minicap#45]
Hi, there is segmentation fault when run minicap in galaxy note4. 
In README.MD, I see description "Also, you'll need to specify the size of the display and the projection every time you use minicap. This is because the private APIs we would have to use to access that information segfault on many Samsung devices". But I specify the size of the display when I run minicap in galaxy note4.
And what's factor or reason caused this phnomemon. And how to locate the reasons.
Thanks for your any help.

**Comment by sorccu** [comment]
Are you 100% sure you're using the latest version of minicap?

**Comment by willysys** [comment]
Thank you very much, the latest version of minicap has no problem. I'm so sorry, I forget to update the version of minicap.

**Comment by sorccu** [comment]
Great!

**Comment by oujibahei** [comment]
@willysys I encounter the same issue also and have used the latest version of minicap on Samsung G9350. How did you solve this problem?

**Comment by MRA11145** [comment]
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 3285252 bytes for JPG encoder

it tried both the way to run but by both the way I got stuck at this point.(way here is easy way and hard way)

there is no progress after  this line.
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 3285252 bytes for JPG encoder
