### ISSUE TITLE
mBufferQueue->setDefaultBufferFormat  with YUV ?

### ISSUE THREAD

**Issue by bstonl** [openstf/minicap#46]
i want the PixelFormat is YUV21(as I have no aosp and too small disk storage)

**Comment by sorccu** [comment]
Sorry, I have no time for that. I'm also not sure if `setDefaultBufferFormat` actually does anything, I recall vaguely that it does not actually affect the output format. The build instructions are complete, I would suggest investing in a larger disk and building it yourself.
