### ISSUE TITLE
minicap 可以打包到apk中运行吗

### ISSUE THREAD

**Issue by sunzcdev** [openstf/minicap#47]
minicap是个so库，是否可以引入到Android Project中，使用java来启动minicap server？

**Comment by sorccu** [comment]
Please post in English only, we don't understand Chinese.

The library can technically be used from Java but you are likely to run into permission issues. The adb shell user has permissions that non-system applications cannot have, at least prior to 5.0.

We don't support that use case but you are free to try by yourself.

**Comment by shatian114** [comment]
可以的，不过手机需要root权限，然后用runtime运行开启的命令就可以了

**Comment by fenggandejiangnan** [comment]
> 可以的，不过手机需要根权限，然后用运行时运行开启的命令就可以了

But if the phone doesn't have root, what if the app gets root? Thanks a lot
