### ISSUE TITLE
Minicap did not accept real display info

### ISSUE THREAD

**Issue by ajaymal87** [openstf/minicap#50]
I am getting the following error in my Minicap use on Nexus 6 (Android 7).

Error:
           INFO: Using projection 1440x2560@360x640/0
           ERROR: (jni/minicap/minicap.cpp:347: errno: None) Minicap did not accept real display info
           INFO: (external/MY_minicap/src/minicap_24.cpp:284) Destroying virtual display

CPU : armeabi-v7a

Command which I am using after which I am getting the error: 

             adb  shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P 1440x2560@360x640/0

**Comment by ajaymal87** [comment]
Can anyone help me in resolving the above issue.
It is not accepting the real display info. I started getting this issue after upgrading my Nexus 6 from Android 6 to Android 7. After upgrading I just replaced the earlier Android-23 minicap.so with the the Android -24 minicap.so and ran the command mentioned in the above comment. 
After all this upgradation I am getting this issue.

**Comment by sorccu** [comment]
Oh wow.. why would you do that? If the libraries worked in every version,
we'd only have one in the first place... you need to update your minicap.
The repository includes the new libs as well.

**Comment by ajaymal87** [comment]
I just replaced the minicap.so from aosp/libs/android-23/minicap.so to aosp/libs/android-24/minicap.so after upgrading my Nexus 6 device from Android-6 to Android-7. 
Did I do anything wrong? Just as a part of upgradation I upgraded the minicap,so as well.

**Comment by sorccu** [comment]
Do not copy the files. Do a fresh clone of the repo or just git pull. The
new libs will be there. Remove the ones you copied first.

**Comment by ajaymal87** [comment]
I did exactly like that but still I am getting the same error as mentioned above.

**Comment by sorccu** [comment]
I strongly believe that it's simply a case of you accidentally using older
or wrong files. All Nexus devices should work just fine with any Android
version.

**Comment by ajaymal87** [comment]
Thanks @sorccu . It was the issue of old binaries only as pointed out by you .. This problem has been resolved now
