### ISSUE TITLE
How to force minicap to publish images?

### ISSUE THREAD

**Issue by sunshine4me** [openstf/minicap#52]
When the screen does not change,minicap  would not send an image.

How to force minicap to publish images? 
or What parameters can it Interval not more than 3 seconds?

**Comment by sorccu** [comment]
You can't. You'd have to change the source code to use ScreenshotClient for
all SDK levels and then rebuild the libraries.

The only way to force a new image right now is to stop minicap and then
start it again, which causes a new frame to be sent.
