### ISSUE TITLE
./run.sh autosize -t works, but ./run.sh autosize abort

### ISSUE THREAD

**Issue by KECB** [openstf/minicap#53]
The `./run.sh autosize -t` will return a 'ok' in the end of the log. 
But `./run.sh autosize` will return a `terminate called after throwing an instance of 'std::bad_cast'  what():  std::bad_cast Aborted ` in the end. I have no idea why this happened. Any idea about how to fix this problem would be great. 
And the full fail log is this:
`+ ndk-build NDK_DEBUG=1 `
`°armeabi-v7aé Gdbserver      : °arm-linux-androideabié libs/armeabi-v7a/gdbserver`
`°armeabi-v7aé Gdbsetup       : libs/armeabi-v7a/gdb.setup`
`°arm64-v8aé Gdbserver      : °aarch64-linux-androidé libs/arm64-v8a/gdbserver`
`°arm64-v8aé Gdbsetup       : libs/arm64-v8a/gdb.setup`
`°x86é Gdbserver      : °i686-linux-androidé libs/x86/gdbserver`
`°x86é Gdbsetup       : libs/x86/gdb.setup`
`°x86_64é Gdbserver      : °x86_64-linux-androidé libs/x86_64/gdbserver`
`°x86_64é Gdbsetup       : libs/x86_64/gdb.setup`
`°armeabi-v7aé Install        : minicap => libs/armeabi-v7a/minicap`
`°armeabi-v7aé Install        : minicap-nopie => libs/armeabi-v7a/minicap-nopie`
`°armeabi-v7aé Install        : minicap.so => libs/armeabi-v7a/minicap.so`
`°arm64-v8aé Install        : minicap => libs/arm64-v8a/minicap`
`°arm64-v8aé Install        : minicap-nopie => libs/arm64-v8a/minicap-nopie`
`°arm64-v8aé Install        : minicap.so => libs/arm64-v8a/minicap.so`
`°x86é Install        : minicap => libs/x86/minicap`
`°x86é Install        : minicap-nopie => libs/x86/minicap-nopie`
`°x86é Install        : minicap.so => libs/x86/minicap.so`
`°x86_64é Install        : minicap => libs/x86_64/minicap`
`°x86_64é Install        : minicap-nopie => libs/x86_64/minicap-nopie`
`°x86_64é Install        : minicap.so => libs/x86_64/minicap.so`
`++ adb shell getprop ro.product.cpu.abi`
`++ tr -d 'çr'`
`+ abi=arm64-v8a`
`++ adb shell getprop ro.build.version.sdk`
`++ tr -d 'çr'`
`+ sdk=23`
`++ adb shell getprop ro.build.version.release`
`++ tr -d 'çr'`
`+ rel=6.0.1`
`+ (( 23 >= 16 ))`
`+ bin=minicap`
`+ args=`
`+ '°' autosize = autosize 'é'`
`+ set +o pipefail`
`++ adb shell dumpsys window`
`++ grep -Eo 'init=çd+xçd+'`
`++ head -1`
`++ cut -d= -f 2`
`+ size=1080x1920`
`+ '°' 1080x1920 = '' 'é'`
`+ args='-P 1080x1920§1080x1920/0'`
`+ set -o pipefail`
`+ shift`
`+ dir=/data/local/tmp/minicap-devel`
`+ adb shell 'mkdir /data/local/tmp/minicap-devel 2>/dev/null òò true'`
`+ adb push libs/arm64-v8a/minicap /data/local/tmp/minicap-devel`
`°100%é /data/local/tmp/minicap-devel/minicap`
`+ '°' -e jni/minicap-shared/aosp/libs/android-6.0.1/arm64-v8a/minicap.so 'é'`
`+ adb push jni/minicap-shared/aosp/libs/android-23/arm64-v8a/minicap.so /data/local/tmp/minicap-devel`
`°100%é /data/local/tmp/minicap-devel/minicap.so`
`+ adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap -P 1080x1920§1080x1920/0`
`PID: 2594`
`INFO: Using projection 1080x1920§1080x1920/0`
`INFO: (external/MY_minicap/src/minicap_23.cpp:240) Creating SurfaceComposerClient`
`INFO: (external/MY_minicap/src/minicap_23.cpp:243) Performing SurfaceComposerClient init check`
`INFO: (external/MY_minicap/src/minicap_23.cpp:250) Creating virtual display`
`INFO: (external/MY_minicap/src/minicap_23.cpp:256) Creating buffer queue`
`INFO: (external/MY_minicap/src/minicap_23.cpp:261) Creating CPU consumer`
`INFO: (external/MY_minicap/src/minicap_23.cpp:265) Creating frame waiter`
`INFO: (external/MY_minicap/src/minicap_23.cpp:269) Publishing virtual display`
`INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder`
`terminate called after throwing an instance of 'std::bad_cast'`
`  what():  std::bad_cast`
`Aborted `

**Comment by sorccu** [comment]
You should have a more detailed stack trace in
logcat.

Honestly though I've never seen this error before, it's probably some kind
of an issue with your setup. Also, the charset of your email is weird,
could possibly be related.

Try another device and/or machine and see if that changes anything.

**Comment by KECB** [comment]
As you guess, it's because of the weird characters, and I just simply reopen the Termianl all back to normal and the command works. 
Thanks for the help.
