### ISSUE TITLE
After startServer ,when phone screen rotation

### ISSUE THREAD

**Issue by sunshine4me** [openstf/minicap#55]
After startServer , when phone screen rotation,I get the img is wrong.
What can i do?
![](https://cdn.rawgit.com/monkeytest15/BlogPNG/5b771f10/dongdong.png)

**Comment by sorccu** [comment]
Read the README. You need to restart minicap with correct parameters when
the device rotates.

**Comment by sunshine4me** [comment]
@sorccu  
When the server has been started , then the user rotate the phone.
Must I to restart minicap server?

**Comment by sorccu** [comment]
Yes, you are required to so. It's written in the README.

**Comment by sunshine4me** [comment]
Thank you for you help an your code!
