### ISSUE TITLE
How to dynamically change parameters

### ISSUE THREAD

**Issue by bbdabing** [openstf/minicap#58]
How to dynamically change parameters
from
LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@144x256/0
to
LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@1440x2560/0

**Comment by sorccu** [comment]
Restart it. That's the only way right now.

**Comment by bbdabing** [comment]
can you tell me how to restart the minicap，i try to kill the pid,but i can't receive the pid when execute this LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@144x256/0，it's 1440x2560 and 144x256.

**Comment by sorccu** [comment]
Well that's not my problem. You can run a shell command like `ps` on the device the retrieve the pid, or use some other method. Please do your own work.

**Comment by bbdabing** [comment]
ok，tks,I'll find another way
