### ISSUE TITLE
how stop minicap

### ISSUE THREAD

**Issue by bbdabing** [openstf/minicap#59]
how stop minicap

**Comment by sorccu** [comment]
Kill it. It shows you the pid, you can use that.

**Comment by bbdabing** [comment]
but when i execute LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@144x256/0 like this,i can't receive the output,  execute LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1440x2560@1440x2560/0 can get the pid ,why!

**Comment by bbdabing** [comment]
String output = executeShellCommand(startCommand);
						if( output!=null ) {
							String[] outputLineArr = output.split("\\r");
							if( outputLineArr!=null && outputLineArr.length>0 ) {
								for(int i=0;i<outputLineArr.length;i++) {
									if( outputLineArr[i].indexOf("PID: ")>=0 ) {
										MINICAP_START_processId = outputLineArr[i].replace("PID: ", "");
										//break;
									}
								}
							}
						}

**Comment by sorccu** [comment]
Maybe it's too small and the system refuses it. Try a larger size.
