### ISSUE TITLE
Use minicap command to take screenshot fail.

### ISSUE THREAD

**Issue by KilmerZhao** [openstf/minicap#6]
Fail to used command "adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 480x854@480x854/0 -t" to take screenshot .

The output info is "/system/bin/sh: /data/local/tmp/minicap: can't execute: Permission denied".

How to solve this problem.

3Q !

**Comment by sorccu** [comment]
Which device is that? On some older android phones, that error message can mean that the executable didn't exist (even though it says permission denied). Make sure that `/data/local/tmp/minicap` is actually there. I would suggest trying to use the run.sh script to make sure everything gets uploaded properly. Also, note that the script puts the binaries into a different folder, `/data/local/tmp/minicap-devel`.

**Comment by KilmerZhao** [comment]
Hi Sorccu:

When build the minicap, the error "/home/kilmer/minicap/minicap-master/jni/vendor/libjpeg-turbo/jni/vendor/libjpeg-turbo/libjpeg-turbo-1.4.1/simd/jsimd_x86_64.c:43: error: undefined reference to 'jconst_rgb_ycc_convert_sse2'" happen.

Is the version of libjpeg-turbo i got is wrong ?

**Comment by sorccu** [comment]
I don't get what you're trying to do. Literally the only thing you need to do is this:

```bash
git clone --recursive https://github.com/openstf/minicap.git
cd minicap
ndk-build
```

OR

```bash
git clone https://github.com/openstf/minicap.git
cd minicap
git submodule init
git submodule update
ndk-build
```

I just tried it and it works fine for me.

**Comment by sorccu** [comment]
Oh, and you MUST use NDK 10e, not any earlier version. That might actually explain it.

**Comment by KilmerZhao** [comment]
Thanks ！

I try it right now.

**Comment by KilmerZhao** [comment]
This is my ndk 'android-ndk64-r10-linux-x86_64.tar.bz2'. 
That might actually explain it.

THANK YOU EVERY MUCH
