### ISSUE TITLE
Limit framerate

### ISSUE THREAD

**Issue by jeckyllhavok** [openstf/minicap#62]
Hi there,
is it possible to limit the framerate in the example app? I just need about 10-15 fps max for my use.
Thanks in advance

**Comment by sorccu** [comment]
Yes and no. If you read the data slower you get less frames (as long as you
specify the skip option - or was it on by default?). It's not perfect
however and may create some lag. That's the only way right now.

**Comment by tangximing** [comment]
hi there, I want to realize the screen capture with 50-60fps, but it results in 10-15fps, Could you tell me how did you do?
