### ISSUE TITLE
The minicap command exit automatic with Android 7.0(SUMSUNG galxy S7 edge).

### ISSUE THREAD

**Issue by JamesChungZLL** [openstf/minicap#63]
The minicap command exit automatic while run with './run.sh autosize'.
Here is output of the command :
-------------------------------------
INFO: Using projection 1440x2560@1440x2560/0
INFO: (external/MY_minicap/src/minicap_24.cpp:240) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_24.cpp:243) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_24.cpp:250) Creating virtual display
INFO: (external/MY_minicap/src/minicap_24.cpp:256) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_24.cpp:261) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_24.cpp:265) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_24.cpp:269) Publishing virtual display
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 11061252 bytes for JPG encoder
INFO: (external/MY_minicap/src/minicap_24.cpp:284) Destroying virtual display

**Comment by sorccu** [comment]
Does the device work in STF?

**Comment by sorccu** [comment]
Also, after finding that out, please also run `adb devices -l` and paste the row for that device. There are so many variations of Galaxy devices that it would be useful to know the exact model. You can remove the serial number if you like.

**Comment by JamesChungZLL** [comment]
I have not tested it on STF platform, but I see the virtual display is destroyed in the log, it may be a fatal issue. And, it will be very helpful to me if this issue is fixed. THANKS! 
-------------------------------------------------------
6afb3a15               device usb:336592896X product:hero2qltezc model:SM_G9350 device:hero2qltechn

**Comment by JamesChungZLL** [comment]
And, it also happens on a other Android 7.0 device 
------------------------------
DLQ0215C23008707       device usb:336592896X product:NXT-DL00 model:HUAWEI_NXT_DL00 device:HWNXT

**Comment by sorccu** [comment]
I don't have that device and it's too expensive for me to buy. Please spend a few minutes testing it in STF and report back whether it works or not.

**Comment by JamesChungZLL** [comment]
It also happens on a other Android 7.0 device
-------------------------------------------
DLQ0215C23008707       device usb:336592896X product:NXT-DL00 model:HUAWEI_NXT_DL00 device:HWNXT

**Comment by sorccu** [comment]
Mate 8 is also too expensive. I do have a Mate S however and it works fine.

**Comment by JamesChungZLL** [comment]
Yes, I could have you remote support if you would like to!

**Comment by sorccu** [comment]
At least SM-G930F (Samsung Galaxy S7) works fine in STF. It's highly unlikely that S7 Edge would not work. I suspect that there's an issue with how you're using minicap. Test your device in STF and see if it works there. If it does work, then you're doing something wrong.

**Comment by JamesChungZLL** [comment]
I run minicap separately, I just use "./run.sh autosize" to start minicap service,.
Yes, Galaxy S7 works fine in STF, but I really do not want minicap command exit after run "./run.sh autosize".

**Comment by JamesChungZLL** [comment]
Hi sorccu, after I reboot the Android deivce, the issue disappear. Sorry for my mistake!!!
However, I am not familiar with js code, could you kindly point out the way STF deal with the screen rotation?

**Comment by JamesChungZLL** [comment]
This issue disappear

**Comment by raoxj** [comment]
> I run minicap separately, I just use "./run.sh autosize" to start minicap service,.
> Yes, Galaxy S7 works fine in STF, but I really do not want minicap command exit after run "./run.sh autosize".

Yes I've met the same problem with you, and it is really strange to me that I still cannot find the answer, and how to resolve this problem
