### ISSUE TITLE
Got a wrong image with minicap.

### ISSUE THREAD

**Issue by JamesChungZLL** [openstf/minicap#64]
6afb3a15 device usb:336592896X product:hero2qltezc model:SM_G9350 device:hero2qltechn
![image](https://cloud.githubusercontent.com/assets/24310832/24862252/7d8f2534-1e2e-11e7-8169-4e036b8056c9.png)

**Comment by sorccu** [comment]
That is what happens if you set the resolution/projection incorrectly.

**Comment by JamesChungZLL** [comment]
I set the resolution/projection "1440x2560@1440x2560/0", which I think is right.

**Comment by JamesChungZLL** [comment]
Hi sorccu, could you please check this issue?

**Comment by sorccu** [comment]
I'm busy, I check issues when I have time. Please do not ask. Does it show up properly in STF? Minicap was made for STF, so it serves as an authoritative example. If it works there, then there's simply something wrong with your usage.

**Comment by tvanderpool** [comment]
I had the same issue, Minicap reports the wrong size in info due to scaling by android. I have a Galaxy S7 which allows for selecting reduced resolutions, the scaling is reported in the logical frame while the physical frame and device width and height still report full size. If you specify the correct projection minicap does work, but AutomatorX for instance relies heavily on the info reported by minicap.

Output from minicap -i & dumpsys display
WQHD setting
```
{
    "id": 0,
    "width": 1440,
    "height": 2560,
    "xdpi": 580.57,
    "ydpi": 575.43,
    "size": 5.09,
    "density": 4.00,
    "fps": 60.00,
    "secure": true,
    "rotation": 0
}

mDefaultViewport=DisplayViewport{valid=true, displayId=0, orientation=0, logicalFrame=Rect(0, 0 - 1440, 2560), physicalFrame=Rect(0, 0 - 1440, 2560), deviceWidth=1440, deviceHeight=2560}
  mExternalTouchViewport=DisplayViewport{valid=false, displayId=0, orientation=0, logicalFrame=Rect(0, 0 - 0, 0), physicalFrame=Rect(0, 0 - 0, 0), deviceWidth=0, deviceHeight=0}
```

FHD setting
```
{
    "id": 0,
    "width": 1440,
    "height": 2560,
    "xdpi": 580.57,
    "ydpi": 575.43,
    "size": 5.09,
    "density": 4.00,
    "fps": 60.00,
    "secure": true,
    "rotation": 0
}

  mDefaultViewport=DisplayViewport{valid=true, displayId=0, orientation=1, logicalFrame=Rect(0, 0 - 1920, 1080), physicalFrame=Rect(0, 0 - 2560, 1440), deviceWidth=2560, deviceHeight=1440}
  mExternalTouchViewport=DisplayViewport{valid=false, displayId=0, orientation=0, logicalFrame=Rect(0, 0 - 0, 0), physicalFrame=Rect(0, 0 - 0, 0), deviceWidth=0, deviceHeight=0
```

In DisplayDeviceInfo the different modes are listed
```
DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 1440 x 2560, modeId 1, defaultModeId 1, supportedModes [{id=1, width=1440, height=2560, fps=60.000004}, {id=2, width=1080, height=1920, fps=60.000004}, {id=3, width=720, height=1280, fps=60.000004}], colorTransformId 1, defaultColorTransformId 1, supportedColorTransforms [{id=1, colorTransform=0}], HdrCapabilities android.view.Display$HdrCapabilities@e3730ec, density 640, 580.571 x 575.433 dpi, appVsyncOff 0, presDeadline 17666666, touch INTERNAL, rotation 0, fixedOrientation -1, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_ROTATES_WITH_CONTENT, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}
```

mCurrentLayerStackRect reports the scaling and DisplayModeRecord reports the current mode and scaling
```
 mCurrentLayerStackRect=Rect(0, 0 - 1080, 1920)
      PhysicalDisplayInfo{1080 x 1920, 60.000004 fps, density 4.0, 580.571 x 575.433 dpi, secure true, appVsyncOffset 0, bufferDeadline 17666666, colorTransform 0}
      DisplayModeRecord{mMode={id=2, width=1080, height=1920, fps=60.000004}}
```

**Comment by sorccu** [comment]
Thanks, that's good info. The info reported by minicap is very raw, and doesn't work on all devices. If you look at STF, you can see that it first attempts to use the public APIs to retrieve the screen size. If that doesn't work (or isn't available on earlier devices), then it falls back to minicap. It should not be relied on 100%.

**Comment by JamesChungZLL** [comment]
@tvanderpool @sorccu So, it seems like set the resolution/projection to "1080x1920@1080x1920/0" will solve this problem.

**Comment by tvanderpool** [comment]
That's what I use on my S7 and it works. However if you are using minicap with minitouch or uiautomator, or something else that is sending taps and the tap is offset from its target, you will have to change the resolution on your phone since many of the tools are not translating the scale correctly.

**Comment by sorccu** [comment]
PRs for minitouch and others are accepted :) Although the mapping should probably be done outside minitouch.

**Comment by JamesChungZLL** [comment]
Yes, @sorccu @tvanderpool ,thank you both.
