### ISSUE TITLE
CANNOT LINK EXECUTABLE....: has text relocations

### ISSUE THREAD

**Issue by tvanderpool** [openstf/minicap#65]
This error is occuring on 7.1, previously versions reported warnings 

+ ndk-build NDK_DEBUG=1
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : libs/armeabi-v7a/gdb.setup
[arm64-v8a] Gdbserver      : [aarch64-linux-android-4.9] libs/arm64-v8a/gdbserver
[arm64-v8a] Gdbsetup       : libs/arm64-v8a/gdb.setup
[x86] Gdbserver      : [x86-4.9] libs/x86/gdbserver
[x86] Gdbsetup       : libs/x86/gdb.setup
[x86_64] Gdbserver      : [x86_64-4.9] libs/x86_64/gdbserver
[x86_64] Gdbsetup       : libs/x86_64/gdb.setup
[armeabi-v7a] Install        : minicap => libs/armeabi-v7a/minicap
[armeabi-v7a] Install        : minicap-nopie => libs/armeabi-v7a/minicap-nopie
[armeabi-v7a] Install        : minicap.so => libs/armeabi-v7a/minicap.so
[arm64-v8a] Install        : minicap => libs/arm64-v8a/minicap
[arm64-v8a] Install        : minicap-nopie => libs/arm64-v8a/minicap-nopie
[arm64-v8a] Install        : minicap.so => libs/arm64-v8a/minicap.so
[x86] Install        : minicap => libs/x86/minicap
[x86] Install        : minicap-nopie => libs/x86/minicap-nopie
[x86] Install        : minicap.so => libs/x86/minicap.so
[x86_64] Install        : minicap => libs/x86_64/minicap
[x86_64] Install        : minicap-nopie => libs/x86_64/minicap-nopie
[x86_64] Install        : minicap.so => libs/x86_64/minicap.so
++ adb shell getprop ro.product.cpu.abi
++ tr -d '\r'
+ abi=x86
++ adb shell getprop ro.build.version.sdk
++ tr -d '\r'
+ sdk=25
++ adb shell getprop ro.build.version.preview_sdk
++ tr -d '\r'
+ pre=0
++ adb shell getprop ro.build.version.release
++ tr -d '\r'
+ rel=7.1.1
+ [[ ! -z 0 ]]
+ sdk=25
+ (( 25 >= 16 ))
+ bin=minicap
+ args=
+ '[' '' = autosize ']'
+ dir=/data/local/tmp/minicap-devel
+ adb shell 'mkdir /data/local/tmp/minicap-devel 2>/dev/null || true'
+ adb push libs/x86/minicap /data/local/tmp/minicap-devel
libs/x86/minicap: 1 file pushed. 218.8 MB/s (997356 bytes in 0.004s)
+ '[' -e jni/minicap-shared/aosp/libs/android-7.1.1/x86/minicap.so ']'
+ adb push jni/minicap-shared/aosp/libs/android-25/x86/minicap.so /data/local/tmp/minicap-devel
jni/minicap-shared/aosp/libs/android-25/x86/minic... 1 file pushed. 26.6 MB/s (17848 bytes in 0.001s)
+ adb shell LD_LIBRARY_PATH=/data/local/tmp/minicap-devel /data/local/tmp/minicap-devel/minicap
CANNOT LINK EXECUTABLE "/data/local/tmp/minicap-devel/minicap": /data/local/tmp/minicap-devel/minicap: has text relocations
Aborted

**Comment by sorccu** [comment]
What kind of an x86 device do you have that runs 7.1?

**Comment by tvanderpool** [comment]
Android SDK emulator

**Comment by sorccu** [comment]
Oh, right... well to be honest minicap was never meant for emulators. It might work but it might not. I can say however that 7.1 on Nexus 5X for example works fine.

If someone has an idea on how to get rid of those warnings, that would be great. I've tried to look into it in the past and played around with compiler flags but could not find a way. There might be more info out there by now, though.

**Comment by tvanderpool** [comment]
With the emulator on 7.1 it's an error and aborts. It works great on the emulator < 7.1 for me at least.

**Comment by sorccu** [comment]
Seems like this can be used to check for it:

```
~/Library/Android/sdk/ndk-bundle/./toolchains/x86-4.9/prebuilt/darwin-x86_64/bin/i686-linux-android-readelf -a prebuilt/x86/bin/minicap | grep TEXTREL
 0x00000016 (TEXTREL)                    0x0
 0x0000001e (FLAGS)                      TEXTREL BIND_NOW
```

Only the x86 binary has that. Weird.

**Comment by tvanderpool** [comment]
Thanks, I've been using this and it wasn't showing in minicap or minicap.so

but I did just find that using that command does show them in libminicap-common.a
```
readelf --wide -S ./obj/local/x86/libminicap-common.a | grep '.rel.text'
  [11] .rel.text._ZN10JpgEncoderC2Ejj REL             00000000 0092e0 000018 08   I 52  10  4
  [13] .rel.text._ZN10JpgEncoderD2Ev REL             00000000 0092f8 000018 08   I 52  12  4
  [20] .rel.text._ZN10JpgEncoder11reserveDataEjj REL             00000000 009310 000048 08   I 52  19  4
  [22] .rel.text._ZN10JpgEncoder13convertFormatEN7Minicap6FormatE REL             00000000 009358 000098 08   I 52  21  4
  [25] .rel.text._ZN10JpgEncoder6encodeEPN7Minicap5FrameEj REL             00000000 0093f0 000040 08   I 52  24  4
  [ 8] .rel.text._ZN12SimpleServerD2Ev REL             00000000 00163c 000018 08   I 34   7  4
  [11] .rel.text._ZN12SimpleServer5startEPKc REL             00000000 001654 000058 08   I 34  10  4
  [13] .rel.text._ZN12SimpleServer6acceptEv REL             00000000 0016ac 000028 08   I 34  12  4
  [13] .rel.text._ZN11FrameWaiterD2Ev REL             00000000 019c04 000020 08   I 65  12  4
  [15] .rel.text._ZN11FrameWaiterD0Ev REL             00000000 019c24 000028 08   I 65  14  4
  [19] .rel.text._ZL14signal_handleri REL             00000000 019c4c 000050 08   I 65  18  4
  [21] .rel.text._ZN11FrameWaiter16onFrameAvailableEv REL             00000000 019c9c 000048 08   I 65  20  4
  [24] .rel.text._ZN10Projection6Parser5parseERS_PKcS3_ REL             00000000 019ce4 000018 08   I 65  23  4
  [28] .rel.text._ZN11FrameWaiter12waitForFrameEv REL             00000000 019d74 000098 08   I 65  27  4
  [31] .rel.text.startup.main REL             00000000 019e0c 0008d8 08   I 65  30  4
  [36] .rel.text.startup._GLOBAL__sub_I_minicap.cpp REL             00000000 01a80c 000090 08   I 65  35  4
```

**Comment by sorccu** [comment]
Interestingly the nopie version seems OK. I also did not see `-fPIC` being passed in the x86 builds, but adding didn't seem to change anything either.

I'm not sure if I'll have time to solve this right now. Hopefully these hints will allow someone to come up with a solution.

**Comment by tvanderpool** [comment]
I was looking into the same thing. I'll give the nopie version a try.

**Comment by sorccu** [comment]
No that one will not work due to other restrictions. However clearly adding the pie flags adds the relocations (they can no longer be seen in the command I posted). It's probably not behaving well with something else. Kind of wondering if the minicap and minicap-nopie targets should include at least one actual file to compile... or perhaps rename main in minicap.cpp and call it from those entry points. Might not have any effect but possibly worth a try.

**Comment by tvanderpool** [comment]
This pull request fixes this issue.
https://github.com/openstf/android-libjpeg-turbo/pull/4

**Comment by DeedleFake** [comment]
How's fixing this going? I'm having the same problem now and it's preventing me from working on a project.

**Comment by tvanderpool** [comment]
For me this pull request for openstf/android-libjpeg-turbo fixed it.
https://github.com/openstf/android-libjpeg-turbo/pull/4

to apply this pull, from the root of your minicap directory
```
cd jni/vendor/libjpeg-turbo
git pull origin pull/4/head
```

**Comment by sorccu** [comment]
Oh... I haven't seen that pull request yet for some reason. I'll try to
merge and update everything this weeekend.
