### ISSUE TITLE
Some code in run.sh can not execute correctly on my Ubuntu 12.04

### ISSUE THREAD

**Issue by KilmerZhao** [openstf/minicap#7]
The script 
'size=$(adb shell dumpsys window | grep -Eo 'init=\d+x\d+' | head -1 | cut -d= -f 2)' 
can not find the string 'init=480x854'

Should change to 
'size=$(adb shell dumpsys window | grep -Eo 'init=[0-9]+x[0-9]+' | head -1 | cut -d= -f 2)'

**Comment by sorccu** [comment]
Closing this issue as it's very old. However Ubuntu 12.04 is too old as well, that was probably the issue. I don't care about supporting ancient build systems.
