### ISSUE TITLE
android-o

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minicap#70]
λ adb shell LD_LIBRARY_PATH=/data/local/tmp /data/local/tmp/minicap -P 1080x1920@1080x1920/0 -t
PID: 12076
INFO: Using projection 1080x1920@1080x1920/0
INFO: (external/MY_minicap/src/minicap_26.cpp:241) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_26.cpp:244) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_26.cpp:255) Creating virtual display
INFO: (external/MY_minicap/src/minicap_26.cpp:261) Creating buffer queue
ERROR: (external/MY_minicap/src/minicap_26.cpp:281: errno: None) Unable to find neither AOSP nor O Developer Pr
eview 1 BufferQueue::createBufferQueue
ERROR: (jni/minicap/minicap.cpp:383: errno: None) Unable to start minicap with current config
INFO: (external/MY_minicap/src/minicap_26.cpp:312) Destroying virtual display

**Comment by sorccu** [comment]
See #67 and https://github.com/openstf/stf/issues/562

**Comment by likezjuisee** [comment]
I have read the issue. But I am not very clearly also.
The android O source code is downloaded by the docker, so it is preview-1 or 2? 
Minicap has not supported the android O yet?

**Comment by sorccu** [comment]
While you can compile against android-o-preview-2, the resulting binary segfaults on my Nexus 5X.

**Comment by likezjuisee** [comment]
I am confused...
How can I fix this error:
Unable to find neither AOSP nor O Developer Preview 1 BufferQueue::createBufferQueue

**Comment by sorccu** [comment]
You can't yet. Like the other issues say, minicap needs a recompile. But even when successfully recompiled against the new branch, it segfaults. Need a workaround for that before we can release.

**Comment by likezjuisee** [comment]
Thank you! Wait for your new release.
