### ISSUE TITLE
ndk-build failed in ndk15

### ISSUE THREAD

**Issue by tccyp001** [openstf/minicap#71]
looks like in the latest ndk version ndk15,  minicap can not ndk-build
download ndk14,  works fine

[armeabi-v7a] Compile++ thumb: minicap-common <= SimpleServer.cpp
jni/minicap/SimpleServer.cpp: In destructor 'SimpleServer::~SimpleServer()':
jni/minicap/SimpleServer.cpp:14:5: error: '::close' has not been declared
     ::close(mFd);
     ^
jni/minicap/SimpleServer.cpp: In member function 'int SimpleServer::start(const char*)':
jni/minicap/SimpleServer.cpp:27:32: error: 'memset' was not declared in this scope
   memset(&addr, 0, sizeof(addr));
                                ^
jni/minicap/SimpleServer.cpp:29:55: error: 'strlen' was not declared in this scope
   strncpy(&addr.sun_path[1], sockname, strlen(sockname));
                                                       ^
jni/minicap/SimpleServer.cpp:29:56: error: 'strncpy' was not declared in this scope
   strncpy(&addr.sun_path[1], sockname, strlen(sockname));
                                                        ^
jni/minicap/SimpleServer.cpp:33:5: error: '::close' has not been declared
     ::close(sfd);
     ^
make: *** [obj/local/armeabi-v7a/objs/minicap-common/SimpleServer.o] Error 1

**Comment by sorccu** [comment]
Should work now, however NDK 15 dropped support for Android 2.3.
