### ISSUE TITLE
How to stop minicap?

### ISSUE THREAD

**Issue by Dan2712** [openstf/minicap#75]
I'm working on the auto orientation, and trying to restart the minicap service when receiving the changing tag. But I cannot find the service by the pid offered by the service. Is there any other ways to do this? thx...

**Comment by BeiKeJieDeLiuLangMao** [comment]
my way is closing adb shell

**Comment by Dan2712** [comment]
got that. thx: )

**Comment by Evan-zch** [comment]
> 我的方式是关闭adb shell

具体怎么做的，能分享一下吗？
