### ISSUE TITLE
How to change the orientation quickly and smooth when the minicap is working ?

### ISSUE THREAD

**Issue by L-Kyle** [openstf/minicap#76]
Thanks to auther with source code firstly ! 　
I have integrated minicap in android application ,now ,I have a problem. I use "LD_LIBRARY_PATH=/data/local/tmp  /data/local/tmp/minicap -P 1080x1920@1080x1920/0" and it works well. I have got the capture of screen. But I found it was uncorrect when the orientation of screen changed,so I reset the parameter when the orientation of screen changed . I use "LD_LIBRARY_PATH=/data/local/tmp  /data/local/tmp/minicap -P 1080x1920@1080x1920/90" but it can't overrite it  witch is working . That's the way I use it, isn't it?  
The way now I am using is to kill the process of minicap in command "pkill minicap" and then restart minicap using "LD_LIBRARY_PATH=...../90". It doesn't work well because using "Runtime.getRuntime().exec("su")" in android cost long time and restart minicap cost time too. It usually cause crash if Ｉrestart minicap too fast.　 How can I do if I want to capture smooth with the changing of screen's orientation？　I don't know whether the param " -t:  Attempt to get the capture method running, then exit.\n" can help me or not . I don't know how to use it. Or it is there a better way ? I'd appreciate it if you told me !

**Comment by sorccu** [comment]
Use the public virtual display API if you want to record the screen
directly on the device.

**Comment by back2chaos** [comment]
I have the same problem.
@L-Kyle Have you solved the problem?
@sorccu  How to use the public virtual display API ? Are there any instructions?

**Comment by sorccu** [comment]
That's a job for the one who gets paid for it (hint: you).
