### ISSUE TITLE
Extra black area in right and bottom for SAMSUNG Galaxy S7

### ISSUE THREAD

**Issue by thulasipavankumar** [openstf/minicap#83]
Image returned  by the minicap library  has extra black area in the right and bottom 
device info 
**_ce10160a918acc2b01     device product:heroltexx model:SM_G930F device:herolte![samsung s7]_**(https://user-images.githubusercontent.com/3539745/28320211-9c8b0f04-6bed-11e7-8a50-26b84a2b37b9.png)

**Comment by sorccu** [comment]
Seems like you've giving it an incorrect resolution. Note that samsung devices often don't use their full resolution by default.

**Comment by thulasipavankumar** [comment]
i tried with run.sh and manually checked the display size of the device with the bellow mentioned command and ran the minicap manually ,in both cases the same image is return by the library :(

"adb shell wm size"

**Comment by sorccu** [comment]
The run.sh script isn't perfect. Try STF and see if it works there (it should).

**Comment by thulasipavankumar** [comment]
@sorccu  Thanks for the quick response 
It's an issue with display settings in the device 
In the settings menu the under display the screen resolution is set to FHD 1080x1920 and its default resolution is WQHD 1440x2560 

After setting to 1440x2560 everything is working fine
