### ISSUE TITLE
Help with Instructions on using minicap without adb

### ISSUE THREAD

**Issue by bageshwar** [openstf/minicap#86]
There are no instructions or detailed steps on using minicap without adb . I understand that the device needs to be rooted for it, but nothing beyond that. 

Any help will be greatly appreciated.

**Comment by sorccu** [comment]
You should use the public virtual display API instead.

**Comment by nancy12Ru** [comment]
Mybe you can use wireless adb . In that case the phone don't need be rooted. and you can use minicap.

**Comment by sorccu** [comment]
Yeah but you’ll still need adb.
