### ISSUE TITLE
Minicap do not work on Android 8.0.0

### ISSUE THREAD

**Issue by JamesChungZLL** [openstf/minicap#88]
Hi Sorccu, the newest Android 8.0.0 has just released, and minicap not work when take a screenshot. Here is the error output:

ERROR: (external/MY_minicap/src/minicap_26.cpp:281: errno: None) Unable to find neither AOSP nor O Developer Preview 1 BufferQueue::createBufferQueue
ERROR: (jni/minicap/minicap.cpp:383: errno: None) Unable to start minicap with current config

Sorry, I have not try STF, For the knowledge I know, It will also not work for STF.
Thanks!

**Comment by sorccu** [comment]
Yeah yeah we already have other issues about this. You just need to wait.

**Comment by JamesChungZLL** [comment]
OK
