### ISSUE TITLE
Building SDK fails

### ISSUE THREAD

**Issue by vbisbest** [openstf/minicap#89]
Build fails when trying to build the sdk.

source build/envsetup.sh
lunch sdk-eng
build sdk -j8

Output
PRODUCT_COPY_FILES frameworks/base/data/sounds/effects/ogg/VideoRecord_48k.ogg:system/media/audio/ui/VideoRecord.ogg ignored.
PRODUCT_COPY_FILES frameworks/base/data/sounds/effects/ogg/VideoStop_48k.ogg:system/media/audio/ui/VideoStop.ogg ignored.
PRODUCT_COPY_FILES frameworks/base/data/sounds/effects/ogg/camera_click_48k.ogg:system/media/audio/ui/camera_click.ogg ignored.
Starting build with ninja
ninja: Entering directory `.'
[  0% 24/27343] build check-support-api
FAILED: /bin/bash -c "frameworks/support/gradlew -p frameworks/support checkApi"
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
Plugin is too old, please update to a more recent version, or set ANDROID_DAILY_OVERRIDE environment variable to "b92c9a05e216ecacee987877b0367e501c51b92"

FAILURE: Build failed with an exception.

* Where:
Build file '/aosp/frameworks/support/graphics/drawable/animated/build.gradle' line: 1

* What went wrong:
A problem occurred evaluating project ':support-animated-vector-drawable'.
> Failed to apply plugin [id 'com.android.library']
   > Could not create plugin of type 'LibraryPlugin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 32.565 secs

Build failed. Possible causes include:
    1) Bad codes
    2) Out of date prebuilts in prebuilts/sdk
    3) Need to update the compileSdkVersion in a library's build.gradle

[  0% 24/27343] host C++: libLLVMBitRe...m/lib/Bitcode/Reader/BitcodeReader.cpp
ninja: build stopped: subcommand failed.
build/core/ninja.mk:148: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1

**Comment by sorccu** [comment]
This doesn't have anything to do with minicap.
