### ISSUE TITLE
Unable to find neither AOSP nor O Developer Preview 1 BufferQueue::createBufferQueue

### ISSUE THREAD

**Issue by yuzhidi** [openstf/minicap#90]
Hi, 
 I have a issue that minicap could not run on Nexus 6P,
[ro.product.manufacturer]: [Huawei]
[ro.product.model]: [Nexus 6P]
[ro.product.name]: [angler]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [8.0.0]
[ro.build.version.sdk]: [26]

could somebody give me some help? thx

**Comment by sorccu** [comment]
PLEASE, read the issues. Android O is NOT supported yet. I get so many people asking about this, it's super frustrating. Please spend 2 minutes looking at the issues and you'll save 2 minutes of my time.

**Comment by yuzhidi** [comment]
I fee sorry
