### ISSUE TITLE
Permission denied on an Android tv

### ISSUE THREAD

**Issue by Namjip** [openstf/minicap#91]
Hey,

i want to run minicap on an Sony Android TV with Android 6.0.1, but it always says permission denied. I've tested it in the /data/local/tmp/minicap and the /data/data/com.android.shell/minicap directorie. I've tested the same on anandroid tab with android 7.0 and and android phone with android 5.1.1 and both worked.
So do you have an idea what is the problem?

Some Product Information:
device product: SVPDTV15_EU model:BRAVIA_2015 device:SVP-DTV15

Thanks in Advance
Namjip

**Comment by sorccu** [comment]
Install it in /data/data/com.android.shell/ instead.

**Comment by sorccu** [comment]
Oh. Nevermind. Not sure then.

**Comment by sorccu** [comment]
Have you made the file executable?

**Comment by Namjip** [comment]
I've build the files with the latest NDK and uses Minicap 2.0.0. It should be executable because it works with the other devices. I've forgotten one thing the TV is not rooted.

**Comment by sorccu** [comment]
Check with ls -l or stat.

**Comment by Namjip** [comment]
When I'm checking i getting the following answer:

shell@SVP-DTV15:/data/local/tmp $ ls -l
-rw-rw-rw- shell    shell      366484 2017-09-01 14:44 minicap
drwxrwxrwx shell    shell             2017-09-04 09:24 minicap-devel
-rw-rw-rw- shell    shell       22128 2017-08-30 16:04 minicap.so

**Comment by sorccu** [comment]
Try making it executable and with chmod 755 then. Then check again. Then
try the same thing in /data/data/com.android.shell/. If both stay
unchanged, then it's a new issue.

**Comment by Namjip** [comment]
That was the Problem. So thank you very much!
