### ISSUE TITLE
download android O source code by docker

### ISSUE THREAD

**Issue by likezjuisee** [openstf/minicap#92]
I downloaded the 5.0.1 succeed, but when I modified the shell command like this from 5.0.1 to 8.0.0, come with the error like below:

root@ubuntu:/home/srv/aosp# docker run -ti --rm -v /home/srv/aosp/android-8.0.0_r1:/aosp -v $PWD/.gitcookies:/root/.gitcookies:ro openstf/aosp:jdk8 /aosp.sh checkout-branch android-8.0.0_r1
error: in `sync`: [Errno 2] No such file or directory: '/aosp/.repo/manifests/.git/HEAD'
error: manifest missing or unreadable -- please run init

**Comment by sorccu** [comment]
Well did you update the mirror first?

**Comment by sorccu** [comment]
I don't see a volume for the mirror. Seems like you're using an incorrect
command.

**Comment by sorccu** [comment]
Like the instructions say you should first sync the mirror with:

```
docker run -ti --rm \
    -v /media/aosp/mirror:/mirror \
    -v $PWD/.gitcookies:/root/.gitcookies:ro \
    openstf/aosp:jdk7 \
    /aosp.sh create-mirror
```

Then run

```
docker run -ti --rm \
    -v /media/aosp/mirror:/mirror \
    -v /media/aosp/android-8.0.0_r1:/aosp \
    -v $PWD/.gitcookies:/root/.gitcookies:ro \
    openstf/aosp:jdk8 \
    /aosp.sh checkout-branch android-8.0.0_r1
```

If you don't want to use the mirror, don't forget the `--no-mirror` flag.

That's all.

**Comment by likezjuisee** [comment]
Yes, I downloaded the source code directly.
Added the no-mirror argument

root@ubuntu:~# docker run -ti --rm -v /home/srv/aosp/android-8.0.0_r1:/aosp -v $PWD/.gitcookies:/root/.gitcookies:ro openstf/aosp:jdk8 /aosp.sh checkout-branch --no-mirror android-8.0.0_r1
error: in `sync`: [Errno 2] No such file or directory: '/aosp/.repo/manifests/.git/HEAD'
error: manifest missing or unreadable -- please run init

**Comment by likezjuisee** [comment]
I have found the reason, that is if the shell command executed before and failed, will created a wrong directory android-8.0.0_r1, then executed the command again will be failed.
I deleted the directory, it began download.

Thx!
