### ISSUE TITLE
minicap not working on Nexus 6P

### ISSUE THREAD

**Issue by tdostilio** [openstf/minicap#97]
**What is the issue or idea you have?**
The screen size is cut off, despite hard coding resolution:  on Huawei Nexus 6p

**Have you tried STF?**

Yes, STF recognizes the device is plugged in but the connection times out.

STF output below:
```
INF/provider 31597 [*] Found device "84B5T15A15002384" (offline)
INF/reaper 31596 [reaper001] Device "84B5T15A15002384" is present
INF/provider 31597 [*] Registered device "84B5T15A15002384"
INF/provider 31597 [*] Providing all 0 of 1 device(s); ignoring "84B5T15A15002384"
INF/reaper 31596 [reaper001] Reaping device "84B5T15A15002384" due to heartbeat timeout
```
I believe this is device specific.

**Comment by sorccu** [comment]
All Nexus devices should work fine. I would suggest sharing more details about your device and application. You should also post the exact command you use to launch minicap.

**Comment by sorccu** [comment]
Look, there are probably hundreds of possible causes. It's a bigger waste of time for me to speculatively list them all, than for you to spend a few minutes detailing your setup. So please do that.

**Comment by tdostilio** [comment]
Sure -- as for my setup, Im running a Nexus 6P in an electron app,  and when I screen record, the screen projection is hardcoded to ```'-P', `1440x2560@1440x2560/0``` but the width and length are cut off. Attaching an image:
<img width="395" alt="screen shot 2017-10-24 at 11 36 52 am" src="https://user-images.githubusercontent.com/26699440/31952887-ac2dd93c-b8af-11e7-8abb-0d83d722db5a.png">

**Comment by sorccu** [comment]
I would suggest taking a screenshot with the `-s` (iirc) option and saving it to /data/local/tmp/screenshot.jpg. Then use `adb pull` to get it out of there. Use Preview or whatever you have on your computer to see if that image is also cropped.

**Comment by tdostilio** [comment]
I followed you instructions, and the screenshot captured was not being cut off:

```
adb shell screencap -p /data/local/tmp/screenshot.jpg
adb pull /data/local/tmp/screenshot.jpg
adb shell rm /data/local/tmp/screenshot.jpg
```
this is the captured screenshot.
![screenshot](https://user-images.githubusercontent.com/26699440/31955517-a1adb804-b8b6-11e7-8dc5-b84ad47a4277.jpg)

**Comment by tdostilio** [comment]
Ok thank you for clarifying that, i will double check my rendering method. Thank you so much for your time and the work you've put in on this. 

I'm still unable to view this device on STF, but to your knowledge all Nexus phones are working? I will double check my phone settings if thats the case.

**Comment by sorccu** [comment]
ADB is telling STF that the device is offline. It could be a hardware issue such as a bad cable or a low powered hub. It could also be that if you try again it might work for a while since you were able to run other adb commands on the device. But that’s basically it, if a device is offline, STF doesn’t touch it.

**Comment by tdostilio** [comment]
Checked render method, nothing amiss there... Still works on my other devices. STF continues to throw this when trying to connect: 

minitouch says: "Note: device /dev/input/mice is not supported by libevdev"
INF/device:plugins:touch 40666 [84B5T15A15002384] minitouch says: "Note: device /dev/input/mouse0 is not supported by libevdev"
INF/device:plugins:touch 40666 [84B5T15A15002384] minitouch says: "Type B touch device synaptics_dsx (1439x2559 with 10 contacts) detected on /dev/input/event0 (score 2109)"
INF/device:plugins:touch 40782 [84B5T15A15002384] minitouch says: "binding socket: Address already in use"
INF/device:plugins:touch 40782 [84B5T15A15002384] minitouch says: "Unable to start server on minitouch"
WRN/device:plugins:touch 40782 [84B5T15A15002384] Shell keeping minitouch running ended unexpectedly
INF/device:plugins:touch 40782 [84B5T15A15002384] Disconnecting from minitouch service
FTL/device:plugins:touch 40782 [84B5T15A15002384] Touch consumer had an error Error: Failed more than 3 times in 10000ms

Running ```stf local``` with my Nexus 6P connected, no special build commands or settings.

**Comment by sorccu** [comment]
You already have minitouch running on that device for some reason. You may have two copies of STF running.

**Comment by tdostilio** [comment]
I've tried everything from unplugging/replugging, to revoking usb debugging auth, and using the command adb kill-server, still not working. Also like I said if I plug in another device such as my HTC phone it picks it up and connects immediately no problems.

**Comment by sorccu** [comment]
You already have minitouch running on the phone. Reboot the phone if you can't figure out why.

**Comment by tdostilio** [comment]
Phone reboot seemed to solve it... Thank you!  Question with regards to the autosize script, where should that be located in the project? In the root folder?

**Comment by sorccu** [comment]
It should just work as is. Be in the project repo folder and run the script.
